import type {
  Approval,
  Attendance,
  AttendanceRecord,
  AuditLog,
  BillingExpense,
  BillingStats,
  ComplianceStats,
  ConsumptionLog,
  DashboardStats,
  Document,
  Expense,
  Invoice,
  Issue,
  Material,
  MaterialRequest,
  Milestone,
  Project,
  PublicComplaint,
  PurchaseOrder,
  Requirement,
  Site,
  SiteStats,
  Task,
  TestReport,
  Transfer,
  TripLog,
  TripStats,
  User,
  Vendor,
} from "@/types";

const now = Date.now();
const day = 86400000;

// ─── Users ────────────────────────────────────────────────────────────────────

export const DEMO_USERS: User[] = [
  {
    id: "u1",
    name: "Rajesh Kumar",
    role: "governmentAuthority",
    email: "govauth@demo.com",
    phone: "+91-9810001001",
    joinedAt: now - 365 * day,
  },
  {
    id: "u2",
    name: "Priya Sharma",
    role: "projectManager",
    email: "pm@demo.com",
    phone: "+91-9810001002",
    joinedAt: now - 300 * day,
  },
  {
    id: "u3",
    name: "Arjun Singh",
    role: "siteEngineer",
    email: "engineer@demo.com",
    phone: "+91-9810001003",
    joinedAt: now - 270 * day,
  },
  {
    id: "u4",
    name: "Vikram Patel",
    role: "contractor",
    email: "contractor@demo.com",
    phone: "+91-9810001004",
    joinedAt: now - 250 * day,
  },
  {
    id: "u5",
    name: "Ravi Yadav",
    role: "worker",
    email: "worker@demo.com",
    phone: "+91-9810001005",
    joinedAt: now - 200 * day,
  },
  {
    id: "u6",
    name: "Meena Iyer",
    role: "auditor",
    email: "auditor@demo.com",
    phone: "+91-9810001006",
    joinedAt: now - 180 * day,
  },
  {
    id: "u7",
    name: "Sunita Verma",
    role: "community",
    email: "community@demo.com",
    phone: "+91-9810001007",
    joinedAt: now - 120 * day,
  },
  {
    id: "u8",
    name: "Anil Mehta",
    role: "public",
    email: "public@demo.com",
    phone: "+91-9810001008",
    joinedAt: now - 90 * day,
  },
];

// ─── Projects ─────────────────────────────────────────────────────────────────

export const PROJECTS: Project[] = [
  {
    id: "p1",
    name: "NH-48 Highway Expansion",
    location: "Delhi-Gurgaon Corridor",
    status: "active",
    budget: 50000000,
    actualCost: 32000000,
    progress: 64,
    startDate: "2024-01-15",
    endDate: "2025-12-31",
    description:
      "6-lane highway expansion project connecting Delhi to Gurgaon with state-of-art infrastructure",
    teamMembers: ["u2", "u3", "u4", "u5"],
    createdBy: "u1",
    createdAt: now - 90 * day,
    milestones: [
      {
        id: "m1_1",
        name: "Land Acquisition & Survey",
        status: "done",
        completionPercent: 100,
        description: "All land parcels acquired and survey completed",
      },
      {
        id: "m1_2",
        name: "Foundation Excavation",
        status: "done",
        completionPercent: 100,
        description: "Excavation of 12km stretch completed",
      },
      {
        id: "m1_3",
        name: "Steel Framework Installation",
        status: "done",
        completionPercent: 85,
        description: "Structural steel framework partially complete",
      },
      {
        id: "m1_4",
        name: "Concrete Carriageway",
        status: "done",
        completionPercent: 60,
        description: "Main carriageway pouring in progress",
      },
      {
        id: "m1_5",
        name: "Drainage & Utilities",
        status: "planned",
        completionPercent: 0,
        description: "Stormwater drainage and utility ducts",
      },
      {
        id: "m1_6",
        name: "Traffic Signals & Signage",
        status: "planned",
        completionPercent: 0,
        description: "Signal installation at 8 junctions",
      },
      {
        id: "m1_7",
        name: "Road Markings & Final Finish",
        status: "planned",
        completionPercent: 0,
        description: "Road paint, reflectors, dividers",
      },
    ],
  },
  {
    id: "p2",
    name: "Government School Complex",
    location: "Sector 45, Noida",
    status: "active",
    budget: 30000000,
    actualCost: 13500000,
    progress: 45,
    startDate: "2024-03-01",
    endDate: "2025-06-30",
    description:
      "Multi-storey school complex with 40 classrooms, labs, library, and sports facilities",
    teamMembers: ["u2", "u3", "u4"],
    createdBy: "u1",
    createdAt: now - 60 * day,
    milestones: [
      {
        id: "m2_1",
        name: "Site Clearing & Leveling",
        status: "done",
        completionPercent: 100,
        description: "Site cleared and leveled for construction",
      },
      {
        id: "m2_2",
        name: "Foundation & Basement",
        status: "done",
        completionPercent: 100,
        description: "Basement parking and raft foundation complete",
      },
      {
        id: "m2_3",
        name: "Ground Floor Construction",
        status: "done",
        completionPercent: 80,
        description: "Ground floor structure nearing completion",
      },
      {
        id: "m2_4",
        name: "Upper Floors (1st–3rd)",
        status: "planned",
        completionPercent: 0,
        description: "Three upper floors with 30 classrooms",
      },
      {
        id: "m2_5",
        name: "Electrical Wiring",
        status: "planned",
        completionPercent: 0,
        description: "Full electrical installation throughout building",
      },
      {
        id: "m2_6",
        name: "Plumbing & Sanitation",
        status: "planned",
        completionPercent: 0,
        description: "Water supply and sewage systems",
      },
      {
        id: "m2_7",
        name: "Interior Finishing & Handover",
        status: "planned",
        completionPercent: 0,
        description: "Plastering, painting, fixtures and final handover",
      },
    ],
  },
  {
    id: "p3",
    name: "Water Treatment Plant",
    location: "Sector 12, Ghaziabad",
    status: "planning",
    budget: 40000000,
    actualCost: 2000000,
    progress: 5,
    startDate: "2024-06-01",
    endDate: "2026-03-31",
    description:
      "Advanced water purification facility serving 500K residents with zero-waste technology",
    teamMembers: ["u2", "u3"],
    createdBy: "u1",
    createdAt: now - 30 * day,
    milestones: [
      {
        id: "m3_1",
        name: "Environmental Impact Assessment",
        status: "done",
        completionPercent: 60,
        description: "EIA report being prepared; clearances pending",
      },
      {
        id: "m3_2",
        name: "Procurement Planning",
        status: "planned",
        completionPercent: 0,
        description: "Vendor contracts and material schedule",
      },
      {
        id: "m3_3",
        name: "Civil Construction",
        status: "planned",
        completionPercent: 0,
        description: "Main plant civil works",
      },
      {
        id: "m3_4",
        name: "Mechanical & Pipe Installation",
        status: "planned",
        completionPercent: 0,
        description: "Treatment machinery and HDPE pipe network",
      },
      {
        id: "m3_5",
        name: "Electrical & Instrumentation",
        status: "planned",
        completionPercent: 0,
        description: "Control systems and SCADA setup",
      },
      {
        id: "m3_6",
        name: "Testing & Commissioning",
        status: "planned",
        completionPercent: 0,
        description: "Quality testing and official handover",
      },
    ],
  },
];

// ─── Sites ────────────────────────────────────────────────────────────────────

export const SITES: Site[] = [
  {
    id: "shouse_1",
    name: "Awas Yojana Phase 1",
    address: "Greater Noida, UP",
    projectId: "phouse_1",
    geoLat: 28.551053225654396,
    geoLng: 77.37215026443997,
    geoRadius: 50,
    status: "active",
    managerName: "Priya Sharma",
    totalWorkers: 42,
    createdAt: now - 30 * day,
  },
  {
    id: "shouse_2",
    name: "Awas Yojana Phase 2",
    address: "Greater Noida, UP",
    projectId: "phouse_2",
    geoLat: 28.52349052692706,
    geoLng: 77.39393304272954,
    geoRadius: 50,
    status: "active",
    managerName: "Priya Sharma",
    totalWorkers: 35,
    createdAt: now - 30 * day,
  },
  {
    id: "shouse_3",
    name: "Awas Yojana Phase 3",
    address: "Greater Noida, UP",
    projectId: "phouse_3",
    geoLat: 28.544810051873778,
    geoLng: 77.40676214489454,
    geoRadius: 50,
    status: "active",
    managerName: "Priya Sharma",
    totalWorkers: 59,
    createdAt: now - 30 * day,
  },
  {
    id: "shouse_4",
    name: "Awas Yojana Phase 4",
    address: "Greater Noida, UP",
    projectId: "phouse_4",
    geoLat: 28.543771602219337,
    geoLng: 77.4118174608853,
    geoRadius: 50,
    status: "active",
    managerName: "Priya Sharma",
    totalWorkers: 51,
    createdAt: now - 30 * day,
  },
  {
    id: "shouse_5",
    name: "Awas Yojana Phase 5",
    address: "Greater Noida, UP",
    projectId: "phouse_5",
    geoLat: 28.5404703824857,
    geoLng: 77.41145188427421,
    geoRadius: 50,
    status: "active",
    managerName: "Priya Sharma",
    totalWorkers: 55,
    createdAt: now - 30 * day,
  },
  {
    id: "shouse_6",
    name: "Awas Yojana Phase 6",
    address: "Greater Noida, UP",
    projectId: "phouse_6",
    geoLat: 28.51065094022426,
    geoLng: 77.403479623443,
    geoRadius: 50,
    status: "active",
    managerName: "Priya Sharma",
    totalWorkers: 62,
    createdAt: now - 30 * day,
  },
  {
    id: "shouse_7",
    name: "Awas Yojana Phase 7",
    address: "Greater Noida, UP",
    projectId: "phouse_7",
    geoLat: 28.544462346551537,
    geoLng: 77.39154617799929,
    geoRadius: 50,
    status: "active",
    managerName: "Priya Sharma",
    totalWorkers: 35,
    createdAt: now - 30 * day,
  },
  {
    id: "shouse_8",
    name: "Awas Yojana Phase 8",
    address: "Greater Noida, UP",
    projectId: "phouse_8",
    geoLat: 28.541746035821536,
    geoLng: 77.38745902569002,
    geoRadius: 50,
    status: "active",
    managerName: "Priya Sharma",
    totalWorkers: 20,
    createdAt: now - 30 * day,
  },
  {
    id: "shouse_9",
    name: "Awas Yojana Phase 9",
    address: "Greater Noida, UP",
    projectId: "phouse_9",
    geoLat: 28.536305495154462,
    geoLng: 77.39556772598665,
    geoRadius: 50,
    status: "active",
    managerName: "Priya Sharma",
    totalWorkers: 48,
    createdAt: now - 30 * day,
  },
  {
    id: "shouse_10",
    name: "Awas Yojana Phase 10",
    address: "Greater Noida, UP",
    projectId: "phouse_10",
    geoLat: 28.543890038420724,
    geoLng: 77.38340116632617,
    geoRadius: 50,
    status: "active",
    managerName: "Priya Sharma",
    totalWorkers: 62,
    createdAt: now - 30 * day,
  },
  {
    id: "shouse_11",
    name: "Awas Yojana Phase 11",
    address: "Greater Noida, UP",
    projectId: "phouse_11",
    geoLat: 28.541517812114993,
    geoLng: 77.37634178316988,
    geoRadius: 50,
    status: "active",
    managerName: "Priya Sharma",
    totalWorkers: 47,
    createdAt: now - 30 * day,
  },
  {
    id: "shouse_12",
    name: "Awas Yojana Phase 12",
    address: "Greater Noida, UP",
    projectId: "phouse_12",
    geoLat: 28.558281287245816,
    geoLng: 77.38618867881503,
    geoRadius: 50,
    status: "active",
    managerName: "Priya Sharma",
    totalWorkers: 70,
    createdAt: now - 30 * day,
  },
  {
    id: "shouse_13",
    name: "Awas Yojana Phase 13",
    address: "Greater Noida, UP",
    projectId: "phouse_13",
    geoLat: 28.5533616424705,
    geoLng: 77.4021312011826,
    geoRadius: 50,
    status: "active",
    managerName: "Priya Sharma",
    totalWorkers: 40,
    createdAt: now - 30 * day,
  },
  {
    id: "shouse_14",
    name: "Awas Yojana Phase 14",
    address: "Greater Noida, UP",
    projectId: "phouse_14",
    geoLat: 28.52263723563369,
    geoLng: 77.39848330944295,
    geoRadius: 50,
    status: "active",
    managerName: "Priya Sharma",
    totalWorkers: 61,
    createdAt: now - 30 * day,
  },
  {
    id: "shouse_15",
    name: "Awas Yojana Phase 15",
    address: "Greater Noida, UP",
    projectId: "phouse_15",
    geoLat: 28.5566306476108,
    geoLng: 77.39379150668354,
    geoRadius: 50,
    status: "active",
    managerName: "Priya Sharma",
    totalWorkers: 29,
    createdAt: now - 30 * day,
  },
  {
    id: "shouse_16",
    name: "Awas Yojana Phase 16",
    address: "Greater Noida, UP",
    projectId: "phouse_16",
    geoLat: 28.525655530143883,
    geoLng: 77.3976689653182,
    geoRadius: 50,
    status: "active",
    managerName: "Priya Sharma",
    totalWorkers: 29,
    createdAt: now - 30 * day,
  },
  {
    id: "shouse_17",
    name: "Awas Yojana Phase 17",
    address: "Greater Noida, UP",
    projectId: "phouse_17",
    geoLat: 28.551448403317682,
    geoLng: 77.39172478039788,
    geoRadius: 50,
    status: "active",
    managerName: "Priya Sharma",
    totalWorkers: 45,
    createdAt: now - 30 * day,
  },
  {
    id: "shouse_18",
    name: "Awas Yojana Phase 18",
    address: "Greater Noida, UP",
    projectId: "phouse_18",
    geoLat: 28.55301512043847,
    geoLng: 77.36627823889565,
    geoRadius: 50,
    status: "active",
    managerName: "Priya Sharma",
    totalWorkers: 36,
    createdAt: now - 30 * day,
  },
  {
    id: "shouse_19",
    name: "Awas Yojana Phase 19",
    address: "Greater Noida, UP",
    projectId: "phouse_19",
    geoLat: 28.515567444676773,
    geoLng: 77.39783345192082,
    geoRadius: 50,
    status: "active",
    managerName: "Priya Sharma",
    totalWorkers: 30,
    createdAt: now - 30 * day,
  },
  {
    id: "shouse_20",
    name: "Awas Yojana Phase 20",
    address: "Greater Noida, UP",
    projectId: "phouse_20",
    geoLat: 28.540962122875655,
    geoLng: 77.3664184318685,
    geoRadius: 50,
    status: "active",
    managerName: "Priya Sharma",
    totalWorkers: 47,
    createdAt: now - 30 * day,
  },
  {
    id: "s1",
    name: "NH-48 Main Site",
    address: "Delhi-Gurgaon Expressway, Milestone 14, New Delhi 110037",
    projectId: "p1",
    geoLat: 28.5244,
    geoLng: 77.1855,
    geoRadius: 100,
    status: "active",
    managerName: "Priya Sharma",
    totalWorkers: 280,
    createdAt: now - 90 * day,
  },
  {
    id: "s2",
    name: "School Complex Site",
    address: "Sector 45, Noida, Uttar Pradesh 201301",
    projectId: "p2",
    geoLat: 28.6139,
    geoLng: 77.3742,
    geoRadius: 100,
    status: "active",
    managerName: "Priya Sharma",
    totalWorkers: 150,
    createdAt: now - 60 * day,
  },
  {
    id: "s3",
    name: "Water Treatment Compound",
    address: "Sector 12, Ghaziabad, Uttar Pradesh 201009",
    projectId: "p3",
    geoLat: 28.6677,
    geoLng: 77.4538,
    geoRadius: 100,
    status: "active",
    managerName: "Priya Sharma",
    totalWorkers: 42,
    createdAt: now - 30 * day,
  },
];

export const SITE_STATS: SiteStats[] = [
  {
    siteId: "s1",
    presentToday: 253,
    totalWorkers: 280,
    tasksInProgress: 4,
    openIssues: 2,
    lastUpdated: now - 30 * 60000,
  },
  {
    siteId: "s2",
    presentToday: 138,
    totalWorkers: 150,
    tasksInProgress: 3,
    openIssues: 1,
    lastUpdated: now - 45 * 60000,
  },
  {
    siteId: "s3",
    presentToday: 38,
    totalWorkers: 42,
    tasksInProgress: 1,
    openIssues: 1,
    lastUpdated: now - 60 * 60000,
  },
];

// ─── Tasks ────────────────────────────────────────────────────────────────────

export const TASKS: Task[] = [
  {
    id: "t1",
    projectId: "p1",
    title: "Foundation Excavation - Zone A",
    description: "Complete excavation of 2km stretch for foundation work",
    assignedTo: "u3",
    status: "completed",
    priority: "critical",
    dueDate: "2024-04-30",
    startDate: "2024-01-20",
    completedAt: now - 45 * day,
    createdBy: "u2",
    createdAt: now - 85 * day,
  },
  {
    id: "t2",
    projectId: "p1",
    title: "Steel Framework Installation",
    description: "Install structural steel framework for elevated sections",
    assignedTo: "u4",
    status: "inProgress",
    priority: "high",
    dueDate: "2024-07-31",
    startDate: "2024-05-01",
    dependencies: ["t1"],
    createdBy: "u2",
    createdAt: now - 80 * day,
  },
  {
    id: "t3",
    projectId: "p1",
    title: "Concrete Pouring - Section 3",
    description: "Pour concrete for the main carriageway section 3",
    assignedTo: "u3",
    status: "inProgress",
    priority: "high",
    dueDate: "2024-08-15",
    startDate: "2024-06-01",
    createdBy: "u2",
    createdAt: now - 75 * day,
  },
  {
    id: "t4",
    projectId: "p1",
    title: "Drainage System Installation",
    description: "Install stormwater drainage along 5km stretch",
    assignedTo: "u4",
    status: "pending",
    priority: "medium",
    dueDate: "2024-09-30",
    startDate: "2024-08-01",
    createdBy: "u2",
    createdAt: now - 70 * day,
  },
  {
    id: "t5",
    projectId: "p1",
    title: "Traffic Signal Setup",
    description: "Install automated traffic management signals at 8 junctions",
    assignedTo: "u3",
    status: "pending",
    priority: "medium",
    dueDate: "2024-11-30",
    startDate: "2024-10-01",
    createdBy: "u2",
    createdAt: now - 65 * day,
  },
  {
    id: "t6",
    projectId: "p2",
    title: "Site Clearing & Leveling",
    description: "Clear site vegetation and level ground for construction",
    assignedTo: "u3",
    status: "completed",
    priority: "high",
    dueDate: "2024-04-15",
    startDate: "2024-03-05",
    completedAt: now - 50 * day,
    createdBy: "u2",
    createdAt: now - 58 * day,
  },
  {
    id: "t7",
    projectId: "p2",
    title: "Basement Construction",
    description: "Construct basement parking structure for 200 vehicles",
    assignedTo: "u4",
    status: "inProgress",
    priority: "high",
    dueDate: "2024-07-30",
    startDate: "2024-05-01",
    dependencies: ["t6"],
    createdBy: "u2",
    createdAt: now - 55 * day,
  },
  {
    id: "t8",
    projectId: "p2",
    title: "Classroom Block A - Ground Floor",
    description: "Construct ground floor of Classroom Block A with 10 rooms",
    assignedTo: "u3",
    status: "pending",
    priority: "medium",
    dueDate: "2024-09-15",
    startDate: "2024-08-01",
    createdBy: "u2",
    createdAt: now - 52 * day,
  },
  {
    id: "t9",
    projectId: "p3",
    title: "Environmental Impact Assessment",
    description: "Complete EIA report and obtain necessary clearances",
    assignedTo: "u3",
    status: "inProgress",
    priority: "critical",
    dueDate: "2024-07-15",
    startDate: "2024-06-05",
    createdBy: "u2",
    createdAt: now - 28 * day,
  },
  {
    id: "t10",
    projectId: "p3",
    title: "Procurement Planning",
    description: "Finalize vendor contracts and material procurement schedule",
    assignedTo: "u4",
    status: "pending",
    priority: "high",
    dueDate: "2024-08-31",
    startDate: "2024-07-16",
    createdBy: "u2",
    createdAt: now - 25 * day,
  },
];

// ─── Issues ───────────────────────────────────────────────────────────────────

export const ISSUES: Issue[] = [
  {
    id: "i1",
    projectId: "p1",
    title: "Unauthorized Sand Mining Detected",
    description:
      "Workers observed extracting sand beyond permitted areas near Km 34 marker. Immediate action required.",
    priority: "critical",
    status: "escalated",
    reportedBy: "u3",
    assignedTo: "u2",
    createdAt: now - 5 * day,
    updatedAt: now - 4 * day,
  },
  {
    id: "i2",
    projectId: "p1",
    title: "Concrete Mix Quality Deviation",
    description:
      "Lab test shows M25 concrete compressive strength 15% below spec at Section 7.",
    priority: "high",
    status: "inProgress",
    reportedBy: "u3",
    assignedTo: "u4",
    createdAt: now - 10 * day,
    updatedAt: now - 8 * day,
  },
  {
    id: "i3",
    projectId: "p2",
    title: "Workers Safety Gear Non-Compliance",
    description:
      "Multiple workers seen without helmets and safety harnesses on upper floor construction zone.",
    priority: "high",
    status: "open",
    reportedBy: "u3",
    createdAt: now - 3 * day,
    updatedAt: now - 3 * day,
  },
  {
    id: "i4",
    projectId: "p2",
    title: "Material Delivery Delay",
    description:
      "Steel rebar delivery delayed by supplier by 2 weeks, causing schedule impact on Block A.",
    priority: "medium",
    status: "inProgress",
    reportedBy: "u4",
    assignedTo: "u2",
    createdAt: now - 7 * day,
    updatedAt: now - 6 * day,
  },
  {
    id: "i5",
    projectId: "p3",
    title: "Survey Equipment Malfunction",
    description:
      "Total station device malfunctioning causing survey delays for EIA boundary mapping.",
    priority: "medium",
    status: "resolved",
    reportedBy: "u3",
    resolvedAt: now - 1 * day,
    createdAt: now - 8 * day,
    updatedAt: now - 1 * day,
  },
];

// ─── Materials ────────────────────────────────────────────────────────────────

export const MATERIALS: Material[] = [
  {
    id: "m1",
    name: "Portland Cement (50kg bags)",
    projectId: "p1",
    unit: "bags",
    quantity: 2400,
    minQuantity: 500,
    unitPrice: 380,
    status: "available",
    lastUpdated: now - 2 * day,
  },
  {
    id: "m2",
    name: "TMT Steel Rebar (Fe500)",
    projectId: "p1",
    unit: "MT",
    quantity: 85,
    minQuantity: 50,
    unitPrice: 68000,
    status: "low",
    lastUpdated: now - 1 * day,
  },
  {
    id: "m3",
    name: "Coarse Aggregate (20mm)",
    projectId: "p1",
    unit: "cum",
    quantity: 320,
    minQuantity: 100,
    unitPrice: 1200,
    status: "available",
    lastUpdated: now - 3 * day,
  },
  {
    id: "m4",
    name: "Portland Cement (50kg bags)",
    projectId: "p2",
    unit: "bags",
    quantity: 40,
    minQuantity: 200,
    unitPrice: 380,
    status: "critical",
    lastUpdated: now - 1 * day,
  },
  {
    id: "m5",
    name: "AAC Blocks (600x200x150)",
    projectId: "p2",
    unit: "pieces",
    quantity: 8500,
    minQuantity: 2000,
    unitPrice: 45,
    status: "available",
    lastUpdated: now - 4 * day,
  },
  {
    id: "m6",
    name: "HDPE Pipes (200mm dia)",
    projectId: "p3",
    unit: "mtrs",
    quantity: 0,
    minQuantity: 500,
    unitPrice: 850,
    status: "outOfStock",
    lastUpdated: now - 5 * day,
  },
];

// ─── Expenses ─────────────────────────────────────────────────────────────────

export const EXPENSES: Expense[] = [
  {
    id: "e1",
    projectId: "p1",
    amount: 4500000,
    category: "Labor",
    description: "Monthly wages for 450 workers – March 2024",
    submittedBy: "u4",
    approvedBy: "u1",
    status: "paid",
    date: "2024-03-31",
    createdAt: now - 25 * day,
  },
  {
    id: "e2",
    projectId: "p1",
    amount: 8200000,
    category: "Materials",
    description: "Steel procurement – Phase 2 milestone delivery",
    submittedBy: "u4",
    approvedBy: "u2",
    status: "paid",
    date: "2024-04-15",
    createdAt: now - 20 * day,
  },
  {
    id: "e3",
    projectId: "p1",
    amount: 1800000,
    category: "Equipment",
    description: "Heavy crane rental for 60 days – Zones A & B",
    submittedBy: "u2",
    status: "approved",
    date: "2024-05-01",
    createdAt: now - 15 * day,
  },
  {
    id: "e4",
    projectId: "p2",
    amount: 2100000,
    category: "Labor",
    description: "Monthly wages for 210 workers – March 2024",
    submittedBy: "u4",
    approvedBy: "u1",
    status: "paid",
    date: "2024-03-31",
    createdAt: now - 25 * day,
  },
  {
    id: "e5",
    projectId: "p2",
    amount: 3400000,
    category: "Materials",
    description: "AAC blocks and cement procurement – Block A",
    submittedBy: "u4",
    status: "pending",
    date: "2024-05-10",
    createdAt: now - 10 * day,
  },
  {
    id: "e6",
    projectId: "p2",
    amount: 620000,
    category: "Services",
    description: "Structural engineering consultation – Month 2",
    submittedBy: "u2",
    approvedBy: "u2",
    status: "approved",
    date: "2024-04-30",
    createdAt: now - 18 * day,
  },
  {
    id: "e7",
    projectId: "p3",
    amount: 850000,
    category: "Services",
    description: "Environmental consultancy for EIA report preparation",
    submittedBy: "u2",
    status: "pending",
    date: "2024-06-10",
    createdAt: now - 8 * day,
  },
  {
    id: "e8",
    projectId: "p3",
    amount: 400000,
    category: "Overhead",
    description: "Temporary site office setup and utilities",
    submittedBy: "u2",
    approvedBy: "u2",
    status: "paid",
    date: "2024-06-05",
    createdAt: now - 12 * day,
  },
];

// ─── Attendance (legacy) ──────────────────────────────────────────────────────

export const ATTENDANCE: Attendance[] = [
  {
    id: "a1",
    workerId: "u5",
    projectId: "p1",
    checkIn: now - 8 * 3600000,
    checkOut: now - 0.5 * 3600000,
    date: new Date().toISOString().split("T")[0],
    status: "present",
  },
  {
    id: "a2",
    workerId: "u5",
    projectId: "p1",
    checkIn: now - day - 9 * 3600000,
    checkOut: now - day - 1 * 3600000,
    date: new Date(now - day).toISOString().split("T")[0],
    status: "present",
  },
  {
    id: "a3",
    workerId: "u5",
    projectId: "p1",
    checkIn: now - 2 * day - 9 * 3600000,
    checkOut: now - 2 * day - 4 * 3600000,
    date: new Date(now - 2 * day).toISOString().split("T")[0],
    status: "halfDay",
  },
  {
    id: "a4",
    workerId: "u5",
    projectId: "p1",
    checkIn: now - 3 * day - 9 * 3600000,
    checkOut: now - 3 * day - 1 * 3600000,
    date: new Date(now - 3 * day).toISOString().split("T")[0],
    status: "present",
  },
  {
    id: "a5",
    workerId: "u5",
    projectId: "p1",
    date: new Date(now - 4 * day).toISOString().split("T")[0],
    checkIn: now - 4 * day,
    status: "absent",
  },
  {
    id: "a6",
    workerId: "u4",
    projectId: "p1",
    checkIn: now - 8 * 3600000,
    checkOut: now - 0.5 * 3600000,
    date: new Date().toISOString().split("T")[0],
    status: "present",
  },
  {
    id: "a7",
    workerId: "u4",
    projectId: "p2",
    checkIn: now - day - 8 * 3600000,
    checkOut: now - day - 0.5 * 3600000,
    date: new Date(now - day).toISOString().split("T")[0],
    status: "present",
  },
  {
    id: "a8",
    workerId: "u3",
    projectId: "p1",
    checkIn: now - 9 * 3600000,
    checkOut: now - 1 * 3600000,
    date: new Date().toISOString().split("T")[0],
    status: "present",
  },
  {
    id: "a9",
    workerId: "u3",
    projectId: "p2",
    checkIn: now - day - 9 * 3600000,
    checkOut: now - day - 1 * 3600000,
    date: new Date(now - day).toISOString().split("T")[0],
    status: "present",
  },
  {
    id: "a10",
    workerId: "u3",
    projectId: "p3",
    date: new Date(now - 2 * day).toISOString().split("T")[0],
    checkIn: now - 2 * day,
    status: "leave",
  },
];

// ─── Attendance Records (new — QR + GPS) ─────────────────────────────────────

export const ATTENDANCE_RECORDS: AttendanceRecord[] = [
  {
    id: "ar1",
    userId: "u5",
    siteId: "s1",
    projectId: "p1",
    date: new Date().toISOString().split("T")[0],
    checkInTime: now - 8 * 3600000,
    checkOutTime: now - 0.5 * 3600000,
    gpsLat: 28.5244,
    gpsLng: 77.1855,
    qrCodeData: "QR_S1_2024",
    locationVerified: true,
    status: "present",
    createdAt: now - 8 * 3600000,
  },
  {
    id: "ar2",
    userId: "u5",
    siteId: "s1",
    projectId: "p1",
    date: new Date(now - day).toISOString().split("T")[0],
    checkInTime: now - day - 9 * 3600000,
    checkOutTime: now - day - 1 * 3600000,
    gpsLat: 28.5244,
    gpsLng: 77.1855,
    locationVerified: true,
    status: "present",
    createdAt: now - day - 9 * 3600000,
  },
  {
    id: "ar3",
    userId: "u4",
    siteId: "s1",
    projectId: "p1",
    date: new Date().toISOString().split("T")[0],
    checkInTime: now - 7.5 * 3600000,
    gpsLat: 28.5244,
    gpsLng: 77.1855,
    locationVerified: true,
    status: "present",
    createdAt: now - 7.5 * 3600000,
  },
  {
    id: "ar4",
    userId: "u3",
    siteId: "s2",
    projectId: "p2",
    date: new Date().toISOString().split("T")[0],
    checkInTime: now - 9 * 3600000,
    checkOutTime: now - 1 * 3600000,
    gpsLat: 28.6139,
    gpsLng: 77.3742,
    locationVerified: true,
    status: "approved",
    approvedBy: "u2",
    createdAt: now - 9 * 3600000,
  },
  {
    id: "ar5",
    userId: "u5",
    siteId: "s1",
    projectId: "p1",
    date: new Date(now - 2 * day).toISOString().split("T")[0],
    locationVerified: false,
    status: "absent",
    createdAt: now - 2 * day,
  },
];

// ─── Vendors ──────────────────────────────────────────────────────────────────

export const VENDORS: Vendor[] = [
  {
    id: "v1",
    name: "Shree Steel Industries",
    contactPerson: "Mohan Lal",
    phone: "+91-9820001010",
    email: "info@shreesteel.com",
    address: "Industrial Area, Sector 8, Faridabad",
    category: "Steel & Metal",
    rating: 4.2,
    createdAt: now - 200 * day,
  },
  {
    id: "v2",
    name: "Rajasthan Cement Corp",
    contactPerson: "Sunita Devi",
    phone: "+91-9830001011",
    email: "sales@rajcement.com",
    address: "Bhiwadi Industrial Area, Rajasthan",
    category: "Cement & Concrete",
    rating: 4.5,
    createdAt: now - 180 * day,
  },
  {
    id: "v3",
    name: "BuildEquip Rentals",
    contactPerson: "Ramesh Gupta",
    phone: "+91-9840001012",
    email: "rentals@buildequip.com",
    address: "Udyog Vihar Phase 2, Gurgaon",
    category: "Equipment & Machinery",
    rating: 3.8,
    createdAt: now - 150 * day,
  },
];

// ─── Purchase Orders ──────────────────────────────────────────────────────────

export const PURCHASE_ORDERS: PurchaseOrder[] = [
  {
    id: "po1",
    siteId: "s1",
    projectId: "p1",
    vendorId: "v1",
    vendorName: "Shree Steel Industries",
    items: [
      {
        id: "pi1",
        name: "TMT Steel Rebar Fe500 (12mm)",
        unit: "MT",
        quantity: 50,
        unitPrice: 68000,
        totalPrice: 3400000,
      },
      {
        id: "pi2",
        name: "Structural Steel Channels",
        unit: "MT",
        quantity: 20,
        unitPrice: 72000,
        totalPrice: 1440000,
      },
    ],
    totalAmount: 4840000,
    status: "approvedL2",
    requestedBy: "u4",
    approvedByL1: "u2",
    approvedByL2: "u1",
    deliveryDate: "2024-07-20",
    notes: "Urgent delivery required for Phase 2 steel framework",
    createdAt: now - 12 * day,
    updatedAt: now - 5 * day,
  },
  {
    id: "po2",
    siteId: "s2",
    projectId: "p2",
    vendorId: "v2",
    vendorName: "Rajasthan Cement Corp",
    items: [
      {
        id: "pi3",
        name: "OPC 53 Grade Cement (50kg)",
        unit: "bags",
        quantity: 800,
        unitPrice: 380,
        totalPrice: 304000,
      },
    ],
    totalAmount: 304000,
    status: "submitted",
    requestedBy: "u4",
    notes: "Replenishment order – stock critical",
    createdAt: now - 3 * day,
    updatedAt: now - 3 * day,
  },
  {
    id: "po3",
    siteId: "s1",
    projectId: "p1",
    vendorId: "v3",
    vendorName: "BuildEquip Rentals",
    items: [
      {
        id: "pi4",
        name: "Tower Crane TC-6024 Rental",
        unit: "months",
        quantity: 3,
        unitPrice: 350000,
        totalPrice: 1050000,
      },
    ],
    totalAmount: 1050000,
    status: "approvedL1",
    requestedBy: "u2",
    approvedByL1: "u2",
    createdAt: now - 8 * day,
    updatedAt: now - 4 * day,
  },
  {
    id: "po4",
    siteId: "s3",
    projectId: "p3",
    vendorId: "v2",
    vendorName: "Rajasthan Cement Corp",
    items: [
      {
        id: "pi5",
        name: "HDPE Pipes 200mm",
        unit: "mtrs",
        quantity: 1000,
        unitPrice: 850,
        totalPrice: 850000,
      },
    ],
    totalAmount: 850000,
    status: "draft",
    requestedBy: "u3",
    createdAt: now - 1 * day,
    updatedAt: now - 1 * day,
  },
];

// ─── Consumption Logs ─────────────────────────────────────────────────────────

export const CONSUMPTION_LOGS: ConsumptionLog[] = [
  {
    id: "cl1",
    siteId: "s1",
    projectId: "p1",
    taskId: "t3",
    materialId: "m1",
    materialName: "Portland Cement (50kg bags)",
    unit: "bags",
    quantity: 120,
    loggedBy: "u3",
    date: "2024-06-10",
    notes: "Used for concrete pouring Section 3",
    createdAt: now - 4 * day,
  },
  {
    id: "cl2",
    siteId: "s1",
    projectId: "p1",
    taskId: "t2",
    materialId: "m2",
    materialName: "TMT Steel Rebar (Fe500)",
    unit: "MT",
    quantity: 35,
    loggedBy: "u4",
    date: "2024-06-08",
    createdAt: now - 6 * day,
  },
  {
    id: "cl3",
    siteId: "s1",
    projectId: "p1",
    taskId: "t3",
    materialId: "m3",
    materialName: "Coarse Aggregate (20mm)",
    unit: "cum",
    quantity: 80,
    loggedBy: "u3",
    date: "2024-06-09",
    notes: "Section 3 concrete work",
    createdAt: now - 5 * day,
  },
  {
    id: "cl4",
    siteId: "s2",
    projectId: "p2",
    taskId: "t7",
    materialId: "m5",
    materialName: "AAC Blocks (600x200x150)",
    unit: "pieces",
    quantity: 1200,
    loggedBy: "u4",
    date: "2024-06-07",
    createdAt: now - 7 * day,
  },
  {
    id: "cl5",
    siteId: "s2",
    projectId: "p2",
    materialId: "m4",
    materialName: "Portland Cement (50kg bags)",
    unit: "bags",
    quantity: 60,
    loggedBy: "u3",
    date: "2024-06-11",
    notes: "Block A plastering work",
    createdAt: now - 3 * day,
  },
];

// ─── Transfers ────────────────────────────────────────────────────────────────

export const TRANSFERS: Transfer[] = [
  {
    id: "tr1",
    fromSiteId: "s1",
    toSiteId: "s2",
    materialId: "m1",
    materialName: "Portland Cement (50kg bags)",
    unit: "bags",
    quantity: 200,
    status: "completed",
    requestedBy: "u2",
    approvedBy: "u2",
    notes: "Emergency transfer to cover critical stock at School site",
    createdAt: now - 5 * day,
    completedAt: now - 3 * day,
  },
  {
    id: "tr2",
    fromSiteId: "s1",
    toSiteId: "s3",
    materialId: "m3",
    materialName: "Coarse Aggregate (20mm)",
    unit: "cum",
    quantity: 50,
    status: "approved",
    requestedBy: "u3",
    approvedBy: "u2",
    createdAt: now - 2 * day,
  },
  {
    id: "tr3",
    fromSiteId: "s2",
    toSiteId: "s1",
    materialId: "m5",
    materialName: "AAC Blocks (600x200x150)",
    unit: "pieces",
    quantity: 500,
    status: "pending",
    requestedBy: "u4",
    notes: "Surplus blocks from School site to NH-48 site",
    createdAt: now - 1 * day,
  },
];

// ─── Trips ────────────────────────────────────────────────────────────────────

export const TRIPS: TripLog[] = [
  {
    id: "tp1",
    siteId: "s1",
    projectId: "p1",
    vehicleNumber: "DL 12 CA 4567",
    vehicleType: "Tipper Truck",
    driverId: "u5",
    driverName: "Ravi Yadav",
    fromLocation: "NH-48 Main Site",
    toLocation: "Faridabad Cement Depot",
    purpose: "Cement pickup – 200 bags",
    status: "completed",
    departureTime: now - 2 * day - 4 * 3600000,
    arrivalTime: now - 2 * day - 1 * 3600000,
    distanceKm: 42,
    fuelCost: 1800,
    approvedBy: "u3",
    createdAt: now - 2 * day - 5 * 3600000,
  },
  {
    id: "tp2",
    siteId: "s1",
    projectId: "p1",
    vehicleNumber: "HR 26 BC 8901",
    vehicleType: "Concrete Mixer",
    driverId: "u5",
    driverName: "Ravi Yadav",
    fromLocation: "Batching Plant, Gurgaon",
    toLocation: "NH-48 Main Site Section 3",
    purpose: "RMC delivery for concrete pouring",
    status: "inProgress",
    departureTime: now - 2 * 3600000,
    distanceKm: 18,
    fuelCost: 900,
    approvedBy: "u4",
    createdAt: now - 3 * 3600000,
  },
  {
    id: "tp3",
    siteId: "s2",
    projectId: "p2",
    vehicleNumber: "UP 80 AB 1234",
    vehicleType: "Pickup Truck",
    driverId: "u5",
    driverName: "Ravi Yadav",
    fromLocation: "School Complex Site",
    toLocation: "Noida Material Supplier",
    purpose: "Steel rebar collection",
    status: "approved",
    approvedBy: "u3",
    createdAt: now - 1 * day,
  },
  {
    id: "tp4",
    siteId: "s3",
    projectId: "p3",
    vehicleNumber: "DL 09 XY 5678",
    vehicleType: "Survey Vehicle",
    driverId: "u3",
    driverName: "Arjun Singh",
    fromLocation: "Water Treatment Compound",
    toLocation: "Ghaziabad District Office",
    purpose: "EIA document submission",
    status: "pending",
    createdAt: now - 6 * 3600000,
  },
];

export const TRIP_STATS: TripStats = {
  siteId: "s1",
  totalTrips: 28,
  completedTrips: 22,
  pendingTrips: 3,
  totalDistanceKm: 1248,
  totalFuelCost: 52400,
};

// ─── Requirements ─────────────────────────────────────────────────────────────

export const REQUIREMENTS: Requirement[] = [
  {
    id: "req1",
    siteId: "s1",
    projectId: "p1",
    title: "Additional TMT Rebar Fe500",
    description:
      "Need 80 MT of 12mm TMT rebar for Phase 2 steel framework completion",
    category: "material",
    quantity: 80,
    unit: "MT",
    urgency: "high",
    status: "approved",
    supplierName: "Shree Steel Industries",
    supplierContact: "+91-9820001010",
    estimatedCost: 5440000,
    requestedBy: "u4",
    approvedBy: "u2",
    requiredByDate: "2024-07-10",
    createdAt: now - 8 * day,
  },
  {
    id: "req2",
    siteId: "s2",
    projectId: "p2",
    title: "Scaffolding Equipment – Block B",
    description:
      "Tubular scaffolding system for 4-storey construction of Block B",
    category: "equipment",
    quantity: 1,
    unit: "set",
    urgency: "critical",
    status: "pending",
    estimatedCost: 280000,
    requestedBy: "u3",
    requiredByDate: "2024-07-05",
    createdAt: now - 3 * day,
  },
  {
    id: "req3",
    siteId: "s3",
    projectId: "p3",
    title: "HDPE Pipes 200mm Dia",
    description:
      "1500 meters of HDPE pipes for water distribution network Phase 1",
    category: "material",
    quantity: 1500,
    unit: "mtrs",
    urgency: "medium",
    status: "ordered",
    supplierName: "Rajasthan Pipes Ltd",
    supplierContact: "+91-9830001020",
    estimatedCost: 1275000,
    requestedBy: "u3",
    approvedBy: "u2",
    requiredByDate: "2024-08-01",
    notes: "PO created – awaiting delivery confirmation",
    createdAt: now - 10 * day,
  },
  {
    id: "req4",
    siteId: "s1",
    projectId: "p1",
    title: "Survey & Marking Labor",
    description:
      "5 additional survey technicians for layout marking of Zones C and D",
    category: "labor",
    quantity: 5,
    unit: "persons",
    urgency: "medium",
    status: "pending",
    estimatedCost: 75000,
    requestedBy: "u3",
    requiredByDate: "2024-07-15",
    createdAt: now - 2 * day,
  },
];

// ─── Invoices ─────────────────────────────────────────────────────────────────

export const INVOICES: Invoice[] = [
  {
    id: "inv1",
    siteId: "s1",
    projectId: "p1",
    vendorId: "v1",
    vendorName: "Shree Steel Industries",
    invoiceNumber: "SSI/2024/0678",
    description: "Supply of TMT Steel Rebar – PO ref po1",
    amount: 4840000,
    taxAmount: 871200,
    totalAmount: 5711200,
    status: "approved",
    submittedBy: "u4",
    approvedBy: "u2",
    dueDate: "2024-07-30",
    createdAt: now - 6 * day,
  },
  {
    id: "inv2",
    siteId: "s1",
    projectId: "p1",
    vendorId: "v3",
    vendorName: "BuildEquip Rentals",
    invoiceNumber: "BER/2024/0345",
    description: "Tower Crane rental – June 2024",
    amount: 350000,
    taxAmount: 63000,
    totalAmount: 413000,
    status: "paid",
    submittedBy: "u2",
    approvedBy: "u1",
    dueDate: "2024-06-30",
    paidAt: now - 2 * day,
    createdAt: now - 20 * day,
  },
  {
    id: "inv3",
    siteId: "s2",
    projectId: "p2",
    vendorId: "v2",
    vendorName: "Rajasthan Cement Corp",
    invoiceNumber: "RCC/2024/0112",
    description: "Cement supply – Block A construction, May batch",
    amount: 304000,
    taxAmount: 54720,
    totalAmount: 358720,
    status: "submitted",
    submittedBy: "u4",
    dueDate: "2024-07-15",
    createdAt: now - 4 * day,
  },
  {
    id: "inv4",
    siteId: "s3",
    projectId: "p3",
    vendorName: "Green Consult Associates",
    invoiceNumber: "GCA/2024/0089",
    description: "EIA report preparation – Phase 1 deliverable",
    amount: 850000,
    taxAmount: 153000,
    totalAmount: 1003000,
    status: "draft",
    submittedBy: "u2",
    dueDate: "2024-08-10",
    createdAt: now - 1 * day,
  },
];

// ─── Billing Expenses ─────────────────────────────────────────────────────────

export const BILLING_EXPENSES: BillingExpense[] = [
  {
    id: "be1",
    siteId: "s1",
    projectId: "p1",
    category: "Labor",
    description: "Skilled labor wages – June 2024 (450 workers)",
    amount: 4500000,
    status: "paid",
    submittedBy: "u4",
    approvedBy: "u1",
    date: "2024-06-30",
    createdAt: now - 4 * day,
  },
  {
    id: "be2",
    siteId: "s1",
    projectId: "p1",
    category: "Equipment",
    description: "Excavator JCB 3DX – monthly rental",
    amount: 180000,
    status: "approved",
    submittedBy: "u4",
    approvedBy: "u2",
    date: "2024-06-15",
    createdAt: now - 8 * day,
  },
  {
    id: "be3",
    siteId: "s2",
    projectId: "p2",
    category: "Materials",
    description: "Waterproofing compound for basement slab",
    amount: 320000,
    status: "pending",
    submittedBy: "u4",
    date: "2024-07-01",
    createdAt: now - 2 * day,
  },
  {
    id: "be4",
    siteId: "s3",
    projectId: "p3",
    category: "Services",
    description: "Soil testing and geo-technical survey",
    amount: 420000,
    status: "approved",
    submittedBy: "u2",
    approvedBy: "u2",
    date: "2024-06-20",
    createdAt: now - 9 * day,
  },
];

export const BILLING_STATS: BillingStats = {
  siteId: "s1",
  totalBudget: 50000000,
  totalInvoiced: 7172920,
  totalPaid: 413000,
  totalExpenses: 4680000,
  budgetUtilization: 24.2,
};

// ─── Test Reports ─────────────────────────────────────────────────────────────

export const TEST_REPORTS: TestReport[] = [
  {
    id: "tr_r1",
    siteId: "s1",
    projectId: "p1",
    taskId: "t3",
    title: "Concrete Compressive Strength Test – Section 3 Batch A",
    testType: "Compressive Strength",
    material: "M25 Concrete",
    standard: "IS 456:2000",
    result: "pass",
    score: 28.4,
    maxScore: 25,
    status: "approvedL2",
    remarks: "Cube strength exceeds IS 456 requirements. Approved.",
    conductedBy: "u3",
    approvedByL1: "u2",
    approvedByL2: "u1",
    testDate: "2024-06-05",
    labName: "Civil Testing Lab, Gurgaon",
    createdAt: now - 9 * day,
  },
  {
    id: "tr_r2",
    siteId: "s1",
    projectId: "p1",
    taskId: "t2",
    title: "Steel Tensile Strength Test – Rebar Batch 7",
    testType: "Tensile Strength",
    material: "TMT Fe500 Rebar 12mm",
    standard: "IS 1786:2008",
    result: "pass",
    score: 540,
    maxScore: 500,
    status: "approvedL1",
    conductedBy: "u3",
    approvedByL1: "u2",
    testDate: "2024-06-01",
    labName: "Metallurgy Lab, Faridabad",
    createdAt: now - 13 * day,
  },
  {
    id: "tr_r3",
    siteId: "s1",
    projectId: "p1",
    title: "Concrete Compressive Strength Test – Section 7 Batch B",
    testType: "Compressive Strength",
    material: "M25 Concrete",
    standard: "IS 456:2000",
    result: "fail",
    score: 21.2,
    maxScore: 25,
    status: "rejected",
    remarks: "Below 25 MPa target. Batch rejected. Rework required.",
    conductedBy: "u3",
    testDate: "2024-05-28",
    labName: "Civil Testing Lab, Gurgaon",
    createdAt: now - 18 * day,
  },
  {
    id: "tr_r4",
    siteId: "s2",
    projectId: "p2",
    title: "Soil Bearing Capacity Test – Basement Zone",
    testType: "Soil Bearing Capacity",
    material: "Native Soil",
    standard: "IS 1888:1982",
    result: "pending",
    status: "submitted",
    conductedBy: "u3",
    testDate: "2024-07-01",
    labName: "Geotech Services, Noida",
    createdAt: now - 1 * day,
  },
];

export const COMPLIANCE_STATS: ComplianceStats = {
  siteId: "s1",
  totalTests: 12,
  passedTests: 9,
  failedTests: 2,
  pendingTests: 1,
  complianceRate: 81.8,
};

// ─── Audit Logs ───────────────────────────────────────────────────────────────

export const AUDIT_LOGS: AuditLog[] = [
  {
    id: "al1",
    userId: "u2",
    userName: "Priya Sharma",
    userRole: "projectManager",
    action: "CREATE",
    entity: "Project",
    entityId: "p3",
    details: "Created project 'Water Treatment Plant' with budget ₹4Cr",
    timestamp: now - 30 * day,
  },
  {
    id: "al2",
    userId: "u1",
    userName: "Rajesh Kumar",
    userRole: "governmentAuthority",
    action: "APPROVE",
    entity: "Budget",
    entityId: "p1",
    details: "Approved budget revision of ₹50L for Phase 2 materials",
    timestamp: now - 28 * day,
  },
  {
    id: "al3",
    userId: "u3",
    userName: "Arjun Singh",
    userRole: "siteEngineer",
    action: "UPDATE",
    entity: "Task",
    entityId: "t1",
    details: "Marked task 'Foundation Excavation Zone A' as Completed",
    timestamp: now - 45 * day,
  },
  {
    id: "al4",
    userId: "u4",
    userName: "Vikram Patel",
    userRole: "contractor",
    action: "SUBMIT",
    entity: "Expense",
    entityId: "e5",
    details: "Submitted expense request ₹34L for AAC blocks and cement",
    timestamp: now - 10 * day,
  },
  {
    id: "al5",
    userId: "u3",
    userName: "Arjun Singh",
    userRole: "siteEngineer",
    action: "REPORT",
    entity: "Issue",
    entityId: "i3",
    details:
      "Reported safety non-compliance: workers without PPE on upper floor",
    timestamp: now - 3 * day,
  },
  {
    id: "al6",
    userId: "u1",
    userName: "Rajesh Kumar",
    userRole: "governmentAuthority",
    action: "VIEW",
    entity: "AuditLog",
    entityId: "all",
    details: "Accessed audit log dashboard",
    timestamp: now - 2 * day,
  },
  {
    id: "al7",
    userId: "u2",
    userName: "Priya Sharma",
    userRole: "projectManager",
    action: "ASSIGN",
    entity: "Task",
    entityId: "t4",
    details: "Assigned Drainage System Installation to Vikram Patel",
    timestamp: now - 65 * day,
  },
  {
    id: "al8",
    userId: "u6",
    userName: "Meena Iyer",
    userRole: "auditor",
    action: "VERIFY",
    entity: "Expense",
    entityId: "e2",
    details: "Verified steel procurement expense ₹82L – documentation complete",
    timestamp: now - 18 * day,
  },
  {
    id: "al9",
    userId: "u4",
    userName: "Vikram Patel",
    userRole: "contractor",
    action: "UPDATE",
    entity: "Material",
    entityId: "m2",
    details: "Updated TMT Steel Rebar inventory: 120MT → 85MT after site usage",
    timestamp: now - 1 * day,
  },
  {
    id: "al10",
    userId: "u3",
    userName: "Arjun Singh",
    userRole: "siteEngineer",
    action: "ESCALATE",
    entity: "Issue",
    entityId: "i1",
    details: "Escalated unauthorized sand mining to Project Manager",
    timestamp: now - 4 * day,
  },
  {
    id: "al11",
    userId: "u2",
    userName: "Priya Sharma",
    userRole: "projectManager",
    action: "APPROVE",
    entity: "Expense",
    entityId: "e3",
    details: "Approved crane rental expense ₹18L for 60-day period",
    timestamp: now - 14 * day,
  },
  {
    id: "al12",
    userId: "u5",
    userName: "Ravi Yadav",
    userRole: "worker",
    action: "CHECKIN",
    entity: "Attendance",
    entityId: "a1",
    details: "QR check-in at NH-48 Site, Zone B",
    timestamp: now - 8 * 3600000,
  },
  {
    id: "al13",
    userId: "u6",
    userName: "Meena Iyer",
    userRole: "auditor",
    action: "REVIEW",
    entity: "Document",
    entityId: "d1",
    details: "Reviewed and approved project completion certificate for Phase 1",
    timestamp: now - 6 * day,
  },
  {
    id: "al14",
    userId: "u1",
    userName: "Rajesh Kumar",
    userRole: "governmentAuthority",
    action: "REJECT",
    entity: "MaterialRequest",
    entityId: "mr1",
    details: "Rejected material request – insufficient documentation provided",
    timestamp: now - 12 * day,
  },
  {
    id: "al15",
    userId: "u3",
    userName: "Arjun Singh",
    userRole: "siteEngineer",
    action: "UPLOAD",
    entity: "Document",
    entityId: "d2",
    details: "Uploaded concrete test report for Section 7 batch samples",
    timestamp: now - 9 * day,
  },
];

// ─── Approvals ────────────────────────────────────────────────────────────────

export const APPROVALS: Approval[] = [
  {
    id: "ap1",
    type: "expense",
    entityId: "e5",
    title: "Material Procurement – AAC Blocks & Cement",
    requestedBy: "u4",
    status: "pending",
    amount: 3400000,
    notes: "Required for Block A construction, Phase 2",
    createdAt: now - 10 * day,
    slaDeadline: now + 2 * day,
  },
  {
    id: "ap2",
    type: "expense",
    entityId: "e7",
    title: "EIA Consultancy Services – Water Treatment Plant",
    requestedBy: "u2",
    status: "pending",
    amount: 850000,
    createdAt: now - 8 * day,
    slaDeadline: now + 4 * day,
  },
  {
    id: "ap3",
    type: "budget",
    entityId: "p2",
    title: "Budget Revision Request – School Complex Phase 2",
    requestedBy: "u2",
    status: "pending",
    amount: 5000000,
    notes: "Cost escalation due to material price hike",
    createdAt: now - 5 * day,
    slaDeadline: now + 7 * day,
  },
  {
    id: "ap4",
    type: "material",
    entityId: "mr1",
    title: "Emergency Steel Rebar Procurement",
    requestedBy: "u4",
    status: "escalated",
    amount: 680000,
    notes: "Stock critically low – production at risk",
    createdAt: now - 3 * day,
    slaDeadline: now + 1 * day,
  },
];

// ─── Dashboard Stats ──────────────────────────────────────────────────────────

export const DASHBOARD_STATS: DashboardStats = {
  totalProjects: 3,
  activeProjects: 2,
  totalTasks: 10,
  pendingTasks: 4,
  openIssues: 3,
  criticalIssues: 1,
  totalBudget: 120000000,
  totalSpent: 47500000,
  workersOnSite: 672,
  pendingApprovals: 4,
};

// ─── Documents (stub for compatibility) ──────────────────────────────────────

export const DOCUMENTS: Document[] = [
  {
    id: "d1",
    projectId: "p1",
    title: "Phase 1 Completion Certificate",
    type: "report",
    fileUrl: "/docs/phase1-completion.pdf",
    fileSize: 248000,
    version: 1,
    uploadedBy: "u2",
    createdAt: now - 20 * day,
    description: "Completion certificate for Phase 1 foundation work",
  },
  {
    id: "d2",
    projectId: "p1",
    title: "Concrete Test Report Section 7",
    type: "report",
    fileUrl: "/docs/concrete-test-s7.pdf",
    fileSize: 145000,
    version: 1,
    uploadedBy: "u3",
    createdAt: now - 9 * day,
  },
];

export const MATERIAL_REQUESTS: MaterialRequest[] = [
  {
    id: "mr1",
    projectId: "p1",
    materialId: "m2",
    requestedBy: "u4",
    quantity: 50,
    urgency: "high",
    status: "approved",
    notes: "Critical shortage – construction at risk",
    createdAt: now - 3 * day,
  },
];

// ─── Public Complaints ────────────────────────────────────────────────────────

export const PUBLIC_COMPLAINTS: PublicComplaint[] = [
  {
    id: 1,
    projectId: "p1",
    projectName: "NH-48 Highway Expansion",
    title: "Debris blocking public road near Km 34",
    description:
      "Construction debris from the highway expansion has been spilling onto the adjacent service road, creating a safety hazard for local residents and vehicles.",
    imageKey: "",
    geoLat: 28.5248,
    geoLng: 77.186,
    reporterName: "Suresh Nair",
    status: "open",
    createdAt: now - 4 * day,
  },
  {
    id: 2,
    projectId: "p1",
    projectName: "NH-48 Highway Expansion",
    title: "Night construction causing noise pollution",
    description:
      "Heavy machinery operating after 10 PM regularly disturbs residents of Sector 18. Promised quiet hours are not being maintained.",
    imageKey: "",
    geoLat: 28.525,
    geoLng: 77.185,
    reporterName: "Kavita Sharma",
    status: "open",
    createdAt: now - 7 * day,
  },
  {
    id: 3,
    projectId: "p2",
    projectName: "Government School Complex",
    title: "Construction wall encroaches on footpath",
    description:
      "The boundary wall erected for the school complex construction has reduced the public footpath to less than 30 cm, making it impassable for wheelchairs and prams.",
    imageKey: "",
    geoLat: 28.614,
    geoLng: 77.374,
    reporterName: "Mohan Tiwari",
    status: "resolved",
    createdAt: now - 15 * day,
  },
  {
    id: 4,
    projectId: "p2",
    projectName: "Government School Complex",
    title: "Dust from construction spreading to nearby homes",
    description:
      "Excessive dust from excavation work at the school site is entering residential apartments in Block C. Anti-dust nets promised were never installed.",
    imageKey: "",
    geoLat: 28.6142,
    geoLng: 77.3745,
    reporterName: "Preethi Menon",
    status: "open",
    createdAt: now - 2 * day,
  },
  {
    id: 5,
    projectId: "p3",
    projectName: "Water Treatment Plant",
    title: "Water supply disrupted without prior notice",
    description:
      "Pipeline work for the water treatment plant cut off water supply to Sector 12 residents for 3 days without any advance communication from the project team.",
    imageKey: "",
    geoLat: 28.668,
    geoLng: 77.454,
    reporterName: "Ramesh Agarwal",
    status: "resolved",
    createdAt: now - 20 * day,
  },
];


// ─── EXPANDED: Additional Project ─────────────────────────────────────────────

export const EXTRA_PROJECTS: Project[] = [
  {
    id: "phouse_1",
    name: "Awas Yojana Phase 1",
    location: "Sector 101, Greater Noida",
    status: "active",
    budget: 5000000,
    actualCost: 2000000,
    progress: 23,
    startDate: "2024-01-01",
    endDate: "2025-12-31",
    description: "Affordable housing construction under PM Awas Yojana.",
    teamMembers: ["u2"],
    createdBy: "u1",
    createdAt: now - 30 * day,
    milestones: []
  },
  {
    id: "phouse_2",
    name: "Awas Yojana Phase 2",
    location: "Sector 102, Greater Noida",
    status: "active",
    budget: 5000000,
    actualCost: 2000000,
    progress: 81,
    startDate: "2024-01-01",
    endDate: "2025-12-31",
    description: "Affordable housing construction under PM Awas Yojana.",
    teamMembers: ["u2"],
    createdBy: "u1",
    createdAt: now - 30 * day,
    milestones: []
  },
  {
    id: "phouse_3",
    name: "Awas Yojana Phase 3",
    location: "Sector 103, Greater Noida",
    status: "active",
    budget: 5000000,
    actualCost: 2000000,
    progress: 82,
    startDate: "2024-01-01",
    endDate: "2025-12-31",
    description: "Affordable housing construction under PM Awas Yojana.",
    teamMembers: ["u2"],
    createdBy: "u1",
    createdAt: now - 30 * day,
    milestones: []
  },
  {
    id: "phouse_4",
    name: "Awas Yojana Phase 4",
    location: "Sector 104, Greater Noida",
    status: "active",
    budget: 5000000,
    actualCost: 2000000,
    progress: 64,
    startDate: "2024-01-01",
    endDate: "2025-12-31",
    description: "Affordable housing construction under PM Awas Yojana.",
    teamMembers: ["u2"],
    createdBy: "u1",
    createdAt: now - 30 * day,
    milestones: []
  },
  {
    id: "phouse_5",
    name: "Awas Yojana Phase 5",
    location: "Sector 105, Greater Noida",
    status: "active",
    budget: 5000000,
    actualCost: 2000000,
    progress: 45,
    startDate: "2024-01-01",
    endDate: "2025-12-31",
    description: "Affordable housing construction under PM Awas Yojana.",
    teamMembers: ["u2"],
    createdBy: "u1",
    createdAt: now - 30 * day,
    milestones: []
  },
  {
    id: "phouse_6",
    name: "Awas Yojana Phase 6",
    location: "Sector 106, Greater Noida",
    status: "active",
    budget: 5000000,
    actualCost: 2000000,
    progress: 18,
    startDate: "2024-01-01",
    endDate: "2025-12-31",
    description: "Affordable housing construction under PM Awas Yojana.",
    teamMembers: ["u2"],
    createdBy: "u1",
    createdAt: now - 30 * day,
    milestones: []
  },
  {
    id: "phouse_7",
    name: "Awas Yojana Phase 7",
    location: "Sector 107, Greater Noida",
    status: "active",
    budget: 5000000,
    actualCost: 2000000,
    progress: 74,
    startDate: "2024-01-01",
    endDate: "2025-12-31",
    description: "Affordable housing construction under PM Awas Yojana.",
    teamMembers: ["u2"],
    createdBy: "u1",
    createdAt: now - 30 * day,
    milestones: []
  },
  {
    id: "phouse_8",
    name: "Awas Yojana Phase 8",
    location: "Sector 108, Greater Noida",
    status: "active",
    budget: 5000000,
    actualCost: 2000000,
    progress: 89,
    startDate: "2024-01-01",
    endDate: "2025-12-31",
    description: "Affordable housing construction under PM Awas Yojana.",
    teamMembers: ["u2"],
    createdBy: "u1",
    createdAt: now - 30 * day,
    milestones: []
  },
  {
    id: "phouse_9",
    name: "Awas Yojana Phase 9",
    location: "Sector 109, Greater Noida",
    status: "active",
    budget: 5000000,
    actualCost: 2000000,
    progress: 19,
    startDate: "2024-01-01",
    endDate: "2025-12-31",
    description: "Affordable housing construction under PM Awas Yojana.",
    teamMembers: ["u2"],
    createdBy: "u1",
    createdAt: now - 30 * day,
    milestones: []
  },
  {
    id: "phouse_10",
    name: "Awas Yojana Phase 10",
    location: "Sector 110, Greater Noida",
    status: "active",
    budget: 5000000,
    actualCost: 2000000,
    progress: 24,
    startDate: "2024-01-01",
    endDate: "2025-12-31",
    description: "Affordable housing construction under PM Awas Yojana.",
    teamMembers: ["u2"],
    createdBy: "u1",
    createdAt: now - 30 * day,
    milestones: []
  },
  {
    id: "phouse_11",
    name: "Awas Yojana Phase 11",
    location: "Sector 111, Greater Noida",
    status: "active",
    budget: 5000000,
    actualCost: 2000000,
    progress: 25,
    startDate: "2024-01-01",
    endDate: "2025-12-31",
    description: "Affordable housing construction under PM Awas Yojana.",
    teamMembers: ["u2"],
    createdBy: "u1",
    createdAt: now - 30 * day,
    milestones: []
  },
  {
    id: "phouse_12",
    name: "Awas Yojana Phase 12",
    location: "Sector 112, Greater Noida",
    status: "active",
    budget: 5000000,
    actualCost: 2000000,
    progress: 55,
    startDate: "2024-01-01",
    endDate: "2025-12-31",
    description: "Affordable housing construction under PM Awas Yojana.",
    teamMembers: ["u2"],
    createdBy: "u1",
    createdAt: now - 30 * day,
    milestones: []
  },
  {
    id: "phouse_13",
    name: "Awas Yojana Phase 13",
    location: "Sector 113, Greater Noida",
    status: "active",
    budget: 5000000,
    actualCost: 2000000,
    progress: 34,
    startDate: "2024-01-01",
    endDate: "2025-12-31",
    description: "Affordable housing construction under PM Awas Yojana.",
    teamMembers: ["u2"],
    createdBy: "u1",
    createdAt: now - 30 * day,
    milestones: []
  },
  {
    id: "phouse_14",
    name: "Awas Yojana Phase 14",
    location: "Sector 114, Greater Noida",
    status: "active",
    budget: 5000000,
    actualCost: 2000000,
    progress: 67,
    startDate: "2024-01-01",
    endDate: "2025-12-31",
    description: "Affordable housing construction under PM Awas Yojana.",
    teamMembers: ["u2"],
    createdBy: "u1",
    createdAt: now - 30 * day,
    milestones: []
  },
  {
    id: "phouse_15",
    name: "Awas Yojana Phase 15",
    location: "Sector 115, Greater Noida",
    status: "active",
    budget: 5000000,
    actualCost: 2000000,
    progress: 60,
    startDate: "2024-01-01",
    endDate: "2025-12-31",
    description: "Affordable housing construction under PM Awas Yojana.",
    teamMembers: ["u2"],
    createdBy: "u1",
    createdAt: now - 30 * day,
    milestones: []
  },
  {
    id: "phouse_16",
    name: "Awas Yojana Phase 16",
    location: "Sector 116, Greater Noida",
    status: "active",
    budget: 5000000,
    actualCost: 2000000,
    progress: 22,
    startDate: "2024-01-01",
    endDate: "2025-12-31",
    description: "Affordable housing construction under PM Awas Yojana.",
    teamMembers: ["u2"],
    createdBy: "u1",
    createdAt: now - 30 * day,
    milestones: []
  },
  {
    id: "phouse_17",
    name: "Awas Yojana Phase 17",
    location: "Sector 117, Greater Noida",
    status: "active",
    budget: 5000000,
    actualCost: 2000000,
    progress: 68,
    startDate: "2024-01-01",
    endDate: "2025-12-31",
    description: "Affordable housing construction under PM Awas Yojana.",
    teamMembers: ["u2"],
    createdBy: "u1",
    createdAt: now - 30 * day,
    milestones: []
  },
  {
    id: "phouse_18",
    name: "Awas Yojana Phase 18",
    location: "Sector 118, Greater Noida",
    status: "active",
    budget: 5000000,
    actualCost: 2000000,
    progress: 64,
    startDate: "2024-01-01",
    endDate: "2025-12-31",
    description: "Affordable housing construction under PM Awas Yojana.",
    teamMembers: ["u2"],
    createdBy: "u1",
    createdAt: now - 30 * day,
    milestones: []
  },
  {
    id: "phouse_19",
    name: "Awas Yojana Phase 19",
    location: "Sector 119, Greater Noida",
    status: "active",
    budget: 5000000,
    actualCost: 2000000,
    progress: 67,
    startDate: "2024-01-01",
    endDate: "2025-12-31",
    description: "Affordable housing construction under PM Awas Yojana.",
    teamMembers: ["u2"],
    createdBy: "u1",
    createdAt: now - 30 * day,
    milestones: []
  },
  {
    id: "phouse_20",
    name: "Awas Yojana Phase 20",
    location: "Sector 120, Greater Noida",
    status: "active",
    budget: 5000000,
    actualCost: 2000000,
    progress: 31,
    startDate: "2024-01-01",
    endDate: "2025-12-31",
    description: "Affordable housing construction under PM Awas Yojana.",
    teamMembers: ["u2"],
    createdBy: "u1",
    createdAt: now - 30 * day,
    milestones: []
  },
  {
    id: "p4",
    name: "Rural Road Connectivity — Mewat",
    location: "Mewat District, Haryana",
    status: "active",
    budget: 22000000,
    actualCost: 9800000,
    progress: 42,
    startDate: "2024-02-01",
    endDate: "2025-08-31",
    description:
      "Construction of 38 km village connecting roads under PM Gram Sadak Yojana to improve last-mile connectivity for 22 villages",
    teamMembers: ["u2", "u3", "u4"],
    createdBy: "u1",
    createdAt: now - 75 * day,
    milestones: [
      { id: "m4_1", name: "Alignment Survey", status: "done", completionPercent: 100, description: "Route finalization and land survey complete" },
      { id: "m4_2", name: "Sub-grade Preparation", status: "done", completionPercent: 100, description: "Earth work and sub-grade leveling done for 28km" },
      { id: "m4_3", name: "WBM Layer", status: "done", completionPercent: 70, description: "Water Bound Macadam base layer — 70% laid" },
      { id: "m4_4", name: "Bituminous Surfacing", status: "planned", completionPercent: 0, description: "Bituminous macadam and seal coat" },
      { id: "m4_5", name: "Cross-drainage Works", status: "planned", completionPercent: 0, description: "Culverts and minor bridges" },
      { id: "m4_6", name: "Road Signs & Markings", status: "planned", completionPercent: 0, description: "Km posts, signage, markings" },
    ],
  },
];

// All projects (base + extra)
export const ALL_PROJECTS: Project[] = [...PROJECTS, ...EXTRA_PROJECTS];

// ─── Worker Profiles ──────────────────────────────────────────────────────────

export interface WorkerProfile {
  id: string;
  name: string;
  trade: string;
  aadhaarId: string;
  ratePerDay: number;
  contractorId: string;
  projectIds: string[];
  phone: string;
  address: string;
  joinedAt: number;
  status: "active" | "inactive" | "onLeave";
}

export const WORKER_PROFILES: WorkerProfile[] = [
  { id: "uw1", name: "Ramesh Kumar", trade: "Mason", aadhaarId: "2847 3901 5623", ratePerDay: 740, contractorId: "u4", projectIds: ["p1", "p4"], phone: "+91-8800001101", address: "Village Palwal, Haryana", joinedAt: now - 180 * day, status: "active" },
  { id: "uw2", name: "Suresh Yadav", trade: "Welder", aadhaarId: "3901 4827 1093", ratePerDay: 880, contractorId: "u4", projectIds: ["p1"], phone: "+91-8800001102", address: "Sector 9, Faridabad", joinedAt: now - 150 * day, status: "active" },
  { id: "uw3", name: "Dinesh Verma", trade: "Electrician", aadhaarId: "5012 3478 9024", ratePerDay: 700, contractorId: "u4", projectIds: ["p2"], phone: "+91-8800001103", address: "Noida, UP", joinedAt: now - 120 * day, status: "active" },
  { id: "uw4", name: "Ganesh Patel", trade: "Carpenter", aadhaarId: "7823 0156 4391", ratePerDay: 770, contractorId: "u4", projectIds: ["p2"], phone: "+91-8800001104", address: "Sector 62, Noida", joinedAt: now - 110 * day, status: "active" },
  { id: "uw5", name: "Ravi Sharma", trade: "Mason", aadhaarId: "1234 5678 9012", ratePerDay: 750, contractorId: "u4", projectIds: ["p1", "p4"], phone: "+91-8800001105", address: "Gurugram, Haryana", joinedAt: now - 200 * day, status: "active" },
  { id: "uw6", name: "Santosh Gupta", trade: "Plumber", aadhaarId: "9876 5432 1098", ratePerDay: 800, contractorId: "u4", projectIds: ["p3"], phone: "+91-8800001106", address: "Ghaziabad, UP", joinedAt: now - 90 * day, status: "active" },
  { id: "uw7", name: "Anil Tiwari", trade: "Helper", aadhaarId: "6543 2109 8765", ratePerDay: 550, contractorId: "u4", projectIds: ["p1", "p2"], phone: "+91-8800001107", address: "Meerut, UP", joinedAt: now - 160 * day, status: "active" },
  { id: "uw8", name: "Bharat Singh", trade: "Shuttering Fitter", aadhaarId: "3210 9876 5432", ratePerDay: 720, contractorId: "u4", projectIds: ["p2"], phone: "+91-8800001108", address: "Bulandshahr, UP", joinedAt: now - 95 * day, status: "active" },
  { id: "uw9", name: "Deepak Nishad", trade: "Bar Bender", aadhaarId: "8765 4321 0987", ratePerDay: 680, contractorId: "u4", projectIds: ["p1"], phone: "+91-8800001109", address: "Moradabad, UP", joinedAt: now - 130 * day, status: "active" },
  { id: "uw10", name: "Kamlesh Yadav", trade: "Road Roller Operator", aadhaarId: "5432 1098 7654", ratePerDay: 950, contractorId: "u4", projectIds: ["p4"], phone: "+91-8800001110", address: "Rewari, Haryana", joinedAt: now - 70 * day, status: "active" },
];

// ─── Wage Requests ─────────────────────────────────────────────────────────────

export interface WageRequest {
  id: string;
  workerId: string;
  workerName: string;
  trade: string;
  projectId: string;
  projectName: string;
  contractorId: string;
  amount: number;
  period: string;
  daysWorked: number;
  ratePerDay: number;
  status: "pending" | "approved" | "rejected" | "paid";
  approvedOn?: string;
  paidOn?: string;
  notes?: string;
  createdAt: number;
}

export const WAGE_REQUESTS: WageRequest[] = [
  { id: "wgr1", workerId: "uw1", workerName: "Ramesh Kumar", trade: "Mason", projectId: "p1", projectName: "NH-48 Highway Expansion", contractorId: "u4", amount: 18500, period: "Apr 2026", daysWorked: 25, ratePerDay: 740, status: "pending", createdAt: now - 3 * day },
  { id: "wgr2", workerId: "uw2", workerName: "Suresh Yadav", trade: "Welder", projectId: "p1", projectName: "NH-48 Highway Expansion", contractorId: "u4", amount: 22000, period: "Apr 2026", daysWorked: 25, ratePerDay: 880, status: "pending", createdAt: now - 3 * day },
  { id: "wgr3", workerId: "uw3", workerName: "Dinesh Verma", trade: "Electrician", projectId: "p2", projectName: "Government School Complex", contractorId: "u4", amount: 11200, period: "Apr 2026", daysWorked: 16, ratePerDay: 700, status: "pending", createdAt: now - 2 * day },
  { id: "wgr4", workerId: "uw9", workerName: "Deepak Nishad", trade: "Bar Bender", projectId: "p1", projectName: "NH-48 Highway Expansion", contractorId: "u4", amount: 17680, period: "Apr 2026", daysWorked: 26, ratePerDay: 680, status: "pending", createdAt: now - 2 * day },
  { id: "wgr5", workerId: "uw10", workerName: "Kamlesh Yadav", trade: "Road Roller Operator", projectId: "p4", projectName: "Rural Road Connectivity", contractorId: "u4", amount: 23750, period: "Apr 2026", daysWorked: 25, ratePerDay: 950, status: "pending", createdAt: now - 1 * day },
  { id: "wgr6", workerId: "uw4", workerName: "Ganesh Patel", trade: "Carpenter", projectId: "p2", projectName: "Government School Complex", contractorId: "u4", amount: 20020, period: "Mar 2026", daysWorked: 26, ratePerDay: 770, status: "paid", approvedOn: "2026-04-02", paidOn: "2026-04-05", createdAt: now - 35 * day },
  { id: "wgr7", workerId: "uw5", workerName: "Ravi Sharma", trade: "Mason", projectId: "p1", projectName: "NH-48 Highway Expansion", contractorId: "u4", amount: 18000, period: "Mar 2026", daysWorked: 24, ratePerDay: 750, status: "paid", approvedOn: "2026-04-02", paidOn: "2026-04-05", createdAt: now - 35 * day },
  { id: "wgr8", workerId: "uw7", workerName: "Anil Tiwari", trade: "Helper", projectId: "p1", projectName: "NH-48 Highway Expansion", contractorId: "u4", amount: 14300, period: "Mar 2026", daysWorked: 26, ratePerDay: 550, status: "paid", approvedOn: "2026-04-03", paidOn: "2026-04-06", createdAt: now - 35 * day },
  { id: "wgr9", workerId: "uw1", workerName: "Ramesh Kumar", trade: "Mason", projectId: "p1", projectName: "NH-48 Highway Expansion", contractorId: "u4", amount: 17020, period: "Mar 2026", daysWorked: 23, ratePerDay: 740, status: "paid", approvedOn: "2026-04-02", paidOn: "2026-04-05", createdAt: now - 35 * day },
  { id: "wgr10", workerId: "uw6", workerName: "Santosh Gupta", trade: "Plumber", projectId: "p3", projectName: "Water Treatment Plant", contractorId: "u4", amount: 14400, period: "Feb 2026", daysWorked: 18, ratePerDay: 800, status: "rejected", notes: "Attendance records mismatch — resubmit with biometric logs", createdAt: now - 65 * day },
  { id: "wgr11", workerId: "uw8", workerName: "Bharat Singh", trade: "Shuttering Fitter", projectId: "p2", projectName: "Government School Complex", contractorId: "u4", amount: 18720, period: "Feb 2026", daysWorked: 26, ratePerDay: 720, status: "paid", approvedOn: "2026-03-02", paidOn: "2026-03-08", createdAt: now - 65 * day },
  { id: "wgr12", workerId: "uw2", workerName: "Suresh Yadav", trade: "Welder", projectId: "p1", projectName: "NH-48 Highway Expansion", contractorId: "u4", amount: 21120, period: "Feb 2026", daysWorked: 24, ratePerDay: 880, status: "paid", approvedOn: "2026-03-02", paidOn: "2026-03-08", createdAt: now - 65 * day },
];

// ─── Worker Payment History ────────────────────────────────────────────────────

export interface WorkerPayment {
  id: string;
  workerId: string;
  amount: number;
  date: string;
  description: string;
  status: "Paid" | "Pending" | "Processing";
  projectId?: string;
}

export const WORKER_PAYMENTS: WorkerPayment[] = [
  { id: "wp1", workerId: "u5", amount: 8500, date: "2026-04-10", description: "Weekly wage – Week 14 (NH-48 Site)", status: "Paid", projectId: "p1" },
  { id: "wp2", workerId: "u5", amount: 1200, date: "2026-04-09", description: "Overtime bonus – Night shift Zone B", status: "Paid", projectId: "p1" },
  { id: "wp3", workerId: "u5", amount: 8500, date: "2026-04-03", description: "Weekly wage – Week 13 (NH-48 Site)", status: "Paid", projectId: "p1" },
  { id: "wp4", workerId: "u5", amount: 8500, date: "2026-03-27", description: "Weekly wage – Week 12 (NH-48 Site)", status: "Paid", projectId: "p1" },
  { id: "wp5", workerId: "u5", amount: 500, date: "2026-03-25", description: "Safety compliance bonus – March", status: "Paid", projectId: "p1" },
  { id: "wp6", workerId: "u5", amount: 8500, date: "2026-03-20", description: "Weekly wage – Week 11 (NH-48 Site)", status: "Paid", projectId: "p1" },
  { id: "wp7", workerId: "u5", amount: 8500, date: "2026-03-13", description: "Weekly wage – Week 10 (Rural Road)", status: "Paid", projectId: "p4" },
  { id: "wp8", workerId: "u5", amount: 8500, date: "2026-04-17", description: "Weekly wage – Week 15 (NH-48 Site)", status: "Pending", projectId: "p1" },
  { id: "wp9", workerId: "u5", amount: 1000, date: "2026-04-15", description: "Public holiday allowance – Ambedkar Jayanti", status: "Processing", projectId: "p1" },
];

// ─── Daily Logs ────────────────────────────────────────────────────────────────

export interface DailyLog {
  id: string;
  projectId: string;
  authorId: string;
  authorName: string;
  date: string;
  weather: string;
  workersPresent: number;
  activitiesDone: string[];
  materialsUsed: { name: string; quantity: number; unit: string }[];
  issuesRaised: string[];
  progressPercent: number;
  notes: string;
  createdAt: number;
}

export const DAILY_LOGS: DailyLog[] = [
  {
    id: "dl1",
    projectId: "p1",
    authorId: "u3",
    authorName: "Arjun Singh",
    date: new Date().toISOString().split("T")[0],
    weather: "Partly cloudy, 34°C",
    workersPresent: 248,
    activitiesDone: [
      "Concrete pouring for Section 3 carriageway — 120 bags cement consumed",
      "Steel reinforcement placement in Zone A piers — 35 MT rebar installed",
      "Drainage trench excavation at Km 18–20 — 120m completed",
      "Traffic diversion updated at Km 14 junction",
    ],
    materialsUsed: [
      { name: "Portland Cement", quantity: 120, unit: "bags" },
      { name: "TMT Rebar Fe500", quantity: 35, unit: "MT" },
      { name: "Coarse Aggregate", quantity: 80, unit: "cum" },
    ],
    issuesRaised: ["Workers in Zone D observed without helmets — safety notice issued"],
    progressPercent: 64,
    notes: "Crane TC-6024 downtime for 2 hours in morning — maintenance done. Work resumed at 10:30 AM. Concrete cube samples taken.",
    createdAt: now - 2 * 3600000,
  },
  {
    id: "dl2",
    projectId: "p1",
    authorId: "u3",
    authorName: "Arjun Singh",
    date: new Date(now - day).toISOString().split("T")[0],
    weather: "Clear sky, 36°C",
    workersPresent: 261,
    activitiesDone: [
      "Steel framework erection in Zone B — 8 piers completed",
      "Concrete pouring for slab at Km 24 — 240 sq.m covered",
      "RMC transit mixer trips: 14 loads (168 cum)",
      "Survey for alignment correction at Km 31",
    ],
    materialsUsed: [
      { name: "RMC M25", quantity: 168, unit: "cum" },
      { name: "TMT Rebar", quantity: 22, unit: "MT" },
    ],
    issuesRaised: [],
    progressPercent: 63,
    notes: "Full day productive. Night shift scheduled for concrete curing inspection.",
    createdAt: now - day - 1 * 3600000,
  },
  {
    id: "dl3",
    projectId: "p2",
    authorId: "u3",
    authorName: "Arjun Singh",
    date: new Date().toISOString().split("T")[0],
    weather: "Hot and humid, 38°C",
    workersPresent: 134,
    activitiesDone: [
      "Block A ground floor slab shuttering complete",
      "Basement waterproofing membrane applied — 600 sq.m",
      "Classroom partition walls in Block B — 12 units started",
      "Electrician conduit laying — 2nd floor east wing completed",
    ],
    materialsUsed: [
      { name: "AAC Blocks", quantity: 800, unit: "pieces" },
      { name: "Portland Cement", quantity: 45, unit: "bags" },
      { name: "Waterproofing Compound", quantity: 24, unit: "drums" },
    ],
    issuesRaised: ["Steel rebar delivery delayed — 2-week impact on Block B schedule"],
    progressPercent: 45,
    notes: "Scaffolding inspection by safety officer: satisfactory. Plumbing rough-in starts tomorrow (Block A).",
    createdAt: now - 3 * 3600000,
  },
  {
    id: "dl4",
    projectId: "p1",
    authorId: "u3",
    authorName: "Arjun Singh",
    date: new Date(now - 2 * day).toISOString().split("T")[0],
    weather: "Overcast, light breeze, 30°C",
    workersPresent: 220,
    activitiesDone: [
      "Asphalt trial strip laid at Km 5 — monitoring underway",
      "Traffic signal pole foundation at Junction 3 — 4 nos. completed",
      "Drainage cover installation — 200m stretch, Km 18–20",
    ],
    materialsUsed: [
      { name: "Asphalt Mix", quantity: 40, unit: "tons" },
      { name: "PCC M10", quantity: 28, unit: "cum" },
    ],
    issuesRaised: ["Unauthorized sand extraction spotted near Km 34 — escalated to PM"],
    progressPercent: 62,
    notes: "Sand mining issue raised with contractor. FIR to be filed if not stopped.",
    createdAt: now - 2 * day - 2 * 3600000,
  },
  {
    id: "dl5",
    projectId: "p4",
    authorId: "u3",
    authorName: "Arjun Singh",
    date: new Date(now - day).toISOString().split("T")[0],
    weather: "Sunny, 40°C, high wind",
    workersPresent: 86,
    activitiesDone: [
      "WBM layer completed for 3 km stretch — Villages 8 to 10",
      "Culvert foundation at Chainage 18+500 — completed",
      "Earthwork side drains — 1.2 km of Villages 11–12",
    ],
    materialsUsed: [
      { name: "Metal / WBM Aggregate", quantity: 340, unit: "cum" },
      { name: "PCC M10 Culvert", quantity: 18, unit: "cum" },
    ],
    issuesRaised: [],
    progressPercent: 42,
    notes: "Wind affected roller work — 1 hour halt. Target of 3 km WBM met. High temperature requiring additional water curing.",
    createdAt: now - day - 4 * 3600000,
  },
];
