/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Approval {
  'id' : UserId,
  'status' : ApprovalStatus,
  'createdAt' : Timestamp,
  'approverRole' : UserRole,
  'entityId' : UserId,
  'notes' : string,
  'entityType' : EntityType,
  'requestedBy' : UserId,
}
export type ApprovalStatus = { 'pending' : null } |
  { 'approved' : null } |
  { 'rejected' : null };
export interface Attendance {
  'id' : UserId,
  'method' : AttendanceMethod,
  'workerId' : UserId,
  'checkIn' : Timestamp,
  'projectId' : UserId,
  'checkOut' : [] | [Timestamp],
  'location' : string,
}
export type AttendanceMethod = { 'qr' : null } |
  { 'gps' : null } |
  { 'manual' : null };
export interface AttendanceRecord {
  'id' : string,
  'status' : AttendanceStatus,
  'qrCodeData' : [] | [string],
  'userId' : UserId,
  'date' : string,
  'approvedBy' : [] | [UserId],
  'photoKey' : [] | [string],
  'checkInTime' : Timestamp,
  'siteId' : string,
  'checkOutTime' : [] | [Timestamp],
  'locationVerified' : boolean,
  'gpsLat' : [] | [number],
  'gpsLng' : [] | [number],
}
export interface AttendanceStats {
  'totalAbsent' : bigint,
  'totalLate' : bigint,
  'totalApproved' : bigint,
  'totalRejected' : bigint,
  'totalPresent' : bigint,
}
export type AttendanceStatus = { 'Present' : null } |
  { 'Late' : null } |
  { 'Approved' : null } |
  { 'Rejected' : null } |
  { 'Absent' : null };
export interface AuditLog {
  'id' : UserId,
  'userName' : string,
  'action' : string,
  'userId' : UserId,
  'entityId' : UserId,
  'timestamp' : Timestamp,
  'details' : string,
  'entityType' : EntityType,
}
export interface BillingExpense {
  'id' : string,
  'status' : ExpenseStatus,
  'receiptKey' : [] | [string],
  'date' : string,
  'approvedBy' : [] | [UserId],
  'createdAt' : Timestamp,
  'submittedBy' : UserId,
  'description' : string,
  'taskId' : [] | [string],
  'category' : ExpenseCategory,
  'siteId' : string,
  'amount' : number,
}
export interface BillingStats {
  'overdueCount' : bigint,
  'totalPaid' : number,
  'totalExpenses' : number,
  'totalPending' : number,
  'totalInvoiced' : number,
}
export interface ComplianceStats {
  'avgScore' : number,
  'totalTests' : bigint,
  'pending' : bigint,
  'failed' : bigint,
  'passed' : bigint,
}
export interface ConsumptionLog {
  'id' : string,
  'date' : string,
  'createdAt' : Timestamp,
  'unit' : string,
  'materialId' : string,
  'taskId' : [] | [string],
  'notes' : [] | [string],
  'quantityConsumed' : number,
  'siteId' : string,
  'materialName' : string,
  'loggedBy' : UserId,
}
export interface ConsumptionSummary {
  'unit' : string,
  'materialId' : string,
  'totalConsumed' : number,
  'materialName' : string,
}
export interface CreatePublicComplaintInput {
  'title' : string,
  'reporterName' : string,
  'description' : string,
  'imageKey' : string,
  'projectId' : string,
  'geoLat' : number,
  'geoLng' : number,
}
export interface DashboardStats {
  'pendingApprovals' : bigint,
  'totalWorkers' : bigint,
  'activeProjects' : bigint,
  'workersPresent' : bigint,
  'totalProjects' : bigint,
  'totalSpent' : number,
  'totalBudget' : number,
}
export interface Document {
  'id' : UserId,
  'title' : string,
  'fileType' : string,
  'version' : bigint,
  'projectId' : UserId,
  'uploadedAt' : Timestamp,
  'uploadedBy' : UserId,
  'fileKey' : string,
}
export type EntityType = { 'expense' : null } |
  { 'task' : null } |
  { 'approval' : null } |
  { 'attendance' : null } |
  { 'issue' : null } |
  { 'material' : null } |
  { 'project' : null };
export interface Expense {
  'id' : UserId,
  'createdAt' : Timestamp,
  'createdBy' : UserId,
  'description' : string,
  'approvalStatus' : ApprovalStatus,
  'projectId' : UserId,
  'category' : string,
  'amount' : number,
}
export type ExpenseCategory = { 'Labor' : null } |
  { 'Overhead' : null } |
  { 'Material' : null } |
  { 'Equipment' : null };
export type ExpenseStatus = { 'Approved' : null } |
  { 'Rejected' : null } |
  { 'Pending' : null };
export interface Invoice {
  'id' : string,
  'status' : InvoiceStatus,
  'createdAt' : Timestamp,
  'dueDate' : string,
  'purchaseOrderId' : [] | [string],
  'paidDate' : [] | [string],
  'invoiceNumber' : string,
  'totalAmount' : number,
  'vendor' : string,
  'siteId' : string,
  'taxAmount' : number,
  'amount' : number,
  'paidBy' : [] | [UserId],
}
export type InvoiceStatus = { 'Paid' : null } |
  { 'Approved' : null } |
  { 'Overdue' : null } |
  { 'Pending' : null };
export interface Issue {
  'id' : UserId,
  'status' : IssueStatus,
  'title' : string,
  'createdAt' : Timestamp,
  'description' : string,
  'imageKey' : string,
  'reportedBy' : UserId,
  'projectId' : UserId,
  'priority' : Priority,
  'location' : string,
}
export type IssueStatus = { 'resolved' : null } |
  { 'closed' : null } |
  { 'acknowledged' : null } |
  { 'reported' : null } |
  { 'inProgress' : null };
export interface Material {
  'id' : UserId,
  'threshold' : number,
  'name' : string,
  'unit' : string,
  'updatedAt' : Timestamp,
  'quantity' : number,
  'category' : string,
  'siteId' : UserId,
}
export interface MaterialRequest {
  'id' : UserId,
  'status' : ApprovalStatus,
  'createdAt' : Timestamp,
  'materialId' : UserId,
  'quantityRequested' : number,
  'projectId' : UserId,
  'notes' : string,
  'requestedBy' : UserId,
}
export type Priority = { 'low' : null } |
  { 'high' : null } |
  { 'critical' : null } |
  { 'medium' : null };
export interface Project {
  'id' : UserId,
  'status' : ProjectStatus,
  'endDate' : string,
  'name' : string,
  'createdAt' : Timestamp,
  'createdBy' : UserId,
  'description' : string,
  'teamMembers' : Array<UserId>,
  'actualCost' : number,
  'progress' : number,
  'budget' : number,
  'location' : string,
  'startDate' : string,
}
export type ProjectStatus = { 'active' : null } |
  { 'cancelled' : null } |
  { 'completed' : null } |
  { 'onHold' : null } |
  { 'planning' : null };
export interface PublicComplaint {
  'id' : bigint,
  'status' : PublicComplaintStatus,
  'title' : string,
  'reporterName' : string,
  'createdAt' : bigint,
  'description' : string,
  'imageKey' : string,
  'projectId' : string,
  'geoLat' : number,
  'geoLng' : number,
}
export type PublicComplaintStatus = { 'resolved' : null } |
  { 'open' : null };
export interface PurchaseItem {
  'qty' : number,
  'rate' : number,
  'unit' : string,
  'amount' : number,
  'materialName' : string,
}
export interface PurchaseOrder {
  'id' : string,
  'attachmentKey' : [] | [string],
  'status' : PurchaseOrderStatus,
  'createdAt' : Timestamp,
  'createdBy' : UserId,
  'deliveryDate' : string,
  'totalAmount' : number,
  'vendorId' : string,
  'approvalLevel1By' : [] | [UserId],
  'approvalLevel2By' : [] | [UserId],
  'siteId' : string,
  'items' : Array<PurchaseItem>,
  'vendorName' : string,
}
export type PurchaseOrderStatus = { 'ApprovedL1' : null } |
  { 'ApprovedL2' : null } |
  { 'Delivered' : null } |
  { 'Draft' : null } |
  { 'Rejected' : null } |
  { 'Submitted' : null };
export interface Requirement {
  'id' : string,
  'supplierContact' : string,
  'status' : RequirementStatus,
  'linkedPurchaseOrderId' : [] | [string],
  'urgency' : Urgency,
  'supplierName' : string,
  'createdAt' : Timestamp,
  'createdBy' : UserId,
  'unit' : string,
  'requiredDate' : string,
  'notes' : [] | [string],
  'approvalLevel1By' : [] | [UserId],
  'approvalLevel2By' : [] | [UserId],
  'quantity' : number,
  'siteId' : string,
  'materialName' : string,
}
export type RequirementStatus = { 'ApprovedL1' : null } |
  { 'ApprovedL2' : null } |
  { 'Draft' : null } |
  { 'Rejected' : null } |
  { 'Submitted' : null } |
  { 'Fulfilled' : null };
export interface Site {
  'id' : string,
  'status' : SiteStatus,
  'name' : string,
  'createdAt' : Timestamp,
  'createdBy' : UserId,
  'geoRadius' : number,
  'address' : string,
  'geoLat' : number,
  'geoLng' : number,
}
export interface SitePicture {
  'id' : UserId,
  'visibleToTenant' : boolean,
  'projectId' : UserId,
  'caption' : string,
  'weekLabel' : string,
  'uploadedAt' : Timestamp,
  'uploadedBy' : UserId,
  'fileKey' : string,
}
export interface SiteStats {
  'totalSites' : bigint,
  'inactiveSites' : bigint,
  'activeSites' : bigint,
}
export type SiteStatus = { 'Inactive' : null } |
  { 'Active' : null };
export interface Task {
  'id' : UserId,
  'status' : TaskStatus,
  'title' : string,
  'assignedTo' : UserId,
  'createdAt' : Timestamp,
  'createdBy' : UserId,
  'dueDate' : string,
  'description' : string,
  'projectId' : UserId,
  'priority' : Priority,
}
export type TaskStatus = { 'pending' : null } |
  { 'completed' : null } |
  { 'inProgress' : null };
export interface TestReport {
  'id' : string,
  'attachmentKey' : [] | [string],
  'status' : TestStatus,
  'testDate' : string,
  'createdAt' : Timestamp,
  'testName' : string,
  'inspectorId' : UserId,
  'taskId' : [] | [string],
  'notes' : [] | [string],
  'approvalLevel1By' : [] | [UserId],
  'approvalLevel2By' : [] | [UserId],
  'siteId' : string,
  'complianceScore' : number,
  'materialType' : string,
}
export type TestStatus = { 'Fail' : null } |
  { 'Pass' : null } |
  { 'Pending' : null };
export type Timestamp = bigint;
export interface Transfer {
  'id' : string,
  'fromSiteId' : string,
  'status' : TransferStatus,
  'transferDate' : string,
  'approvedBy' : [] | [UserId],
  'createdAt' : Timestamp,
  'createdBy' : UserId,
  'unit' : string,
  'materialId' : string,
  'quantity' : number,
  'materialName' : string,
  'toSiteId' : string,
  'reason' : string,
}
export type TransferStatus = { 'Approved' : null } |
  { 'Rejected' : null } |
  { 'Completed' : null } |
  { 'Pending' : null };
export interface TripLog {
  'id' : string,
  'status' : TripStatus,
  'vehicleName' : string,
  'driverId' : string,
  'tripDate' : string,
  'ratePerKm' : number,
  'approvedBy' : [] | [UserId],
  'createdAt' : Timestamp,
  'createdBy' : UserId,
  'totalCost' : number,
  'distance' : number,
  'fuelConsumed' : number,
  'endLocation' : string,
  'siteId' : string,
  'driverName' : string,
  'purpose' : string,
  'startLocation' : string,
  'vehicleId' : string,
}
export interface TripStats {
  'pendingApprovals' : bigint,
  'totalTrips' : bigint,
  'totalCost' : number,
  'totalFuel' : number,
  'totalDistance' : number,
}
export type TripStatus = { 'Approved' : null } |
  { 'Rejected' : null } |
  { 'Pending' : null };
export type Urgency = { 'Low' : null } |
  { 'High' : null } |
  { 'Medium' : null } |
  { 'Critical' : null };
export interface User {
  'id' : UserId,
  'name' : string,
  'createdAt' : Timestamp,
  'role' : UserRole,
  'email' : string,
}
export type UserId = string;
export type UserRole = { 'publicUser' : null } |
  { 'community' : null } |
  { 'projectManager' : null } |
  { 'auditor' : null } |
  { 'governmentAuthority' : null } |
  { 'worker' : null } |
  { 'tenant' : null } |
  { 'contractor' : null } |
  { 'siteEngineer' : null };
export type UserRole__1 = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface Vendor {
  'id' : string,
  'contact' : string,
  'name' : string,
  'email' : string,
  'address' : string,
  'rating' : number,
}
export interface WeeklyProgress {
  'id' : UserId,
  'writtenBy' : UserId,
  'status' : string,
  'approvedAt' : [] | [string],
  'createdAt' : Timestamp,
  'pmProgressRef' : string,
  'progressNotes' : string,
  'projectId' : UserId,
  'communityNotes' : string,
  'weekLabel' : string,
  'photos' : Array<string>,
}
export interface _SERVICE {
  '_initializeAccessControl' : ActorMethod<[], undefined>,
  'approveAttendance' : ActorMethod<[string], boolean>,
  'approveExpense' : ActorMethod<[string, boolean], [] | [Expense]>,
  'approveExpenseRecord' : ActorMethod<[string], boolean>,
  'approveInvoice' : ActorMethod<[string], boolean>,
  'approveMaterialRequest' : ActorMethod<
    [string, boolean, string],
    [] | [MaterialRequest]
  >,
  'approvePurchaseOrderL1' : ActorMethod<[string], boolean>,
  'approvePurchaseOrderL2' : ActorMethod<[string], boolean>,
  'approveRequirementL1' : ActorMethod<[string], boolean>,
  'approveRequirementL2' : ActorMethod<[string], boolean>,
  'approveTestReportL1' : ActorMethod<[string], boolean>,
  'approveTestReportL2' : ActorMethod<[string], boolean>,
  'approveTransfer' : ActorMethod<[string], boolean>,
  'approveTrip' : ActorMethod<[string], boolean>,
  'approveWeeklyProgress' : ActorMethod<
    [string, string, string],
    [] | [WeeklyProgress]
  >,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole__1], undefined>,
  'checkoutAttendance' : ActorMethod<[string], [] | [Attendance]>,
  'completeTransfer' : ActorMethod<[string], boolean>,
  'createApproval' : ActorMethod<
    [EntityType, string, UserRole, string],
    Approval
  >,
  'createBillingExpense' : ActorMethod<
    [
      string,
      [] | [string],
      ExpenseCategory,
      string,
      number,
      string,
      [] | [string],
    ],
    BillingExpense
  >,
  'createExpense' : ActorMethod<[string, number, string, string], Expense>,
  'createInvoice' : ActorMethod<
    [string, [] | [string], string, string, number, number, number, string],
    Invoice
  >,
  'createIssue' : ActorMethod<
    [string, string, string, string, Priority, string],
    Issue
  >,
  'createMaterialRequest' : ActorMethod<
    [string, string, number, string],
    MaterialRequest
  >,
  'createProject' : ActorMethod<
    [string, string, number, string, string, string],
    Project
  >,
  'createPublicComplaint' : ActorMethod<[CreatePublicComplaintInput], bigint>,
  'createPurchaseOrder' : ActorMethod<
    [
      string,
      string,
      string,
      Array<PurchaseItem>,
      number,
      string,
      [] | [string],
    ],
    PurchaseOrder
  >,
  'createRequirement' : ActorMethod<
    [
      string,
      string,
      number,
      string,
      Urgency,
      string,
      string,
      string,
      [] | [string],
    ],
    Requirement
  >,
  'createSite' : ActorMethod<[string, string, number, number, number], Site>,
  'createTask' : ActorMethod<
    [string, string, string, string, Priority, string],
    Task
  >,
  'createTestReport' : ActorMethod<
    [
      string,
      [] | [string],
      string,
      string,
      string,
      number,
      [] | [string],
      [] | [string],
    ],
    TestReport
  >,
  'createTransfer' : ActorMethod<
    [string, string, string, string, number, string, string, string],
    Transfer
  >,
  'createTrip' : ActorMethod<
    [
      string,
      string,
      string,
      string,
      string,
      string,
      string,
      string,
      number,
      string,
      number,
      number,
      number,
    ],
    TripLog
  >,
  'createVendor' : ActorMethod<
    [string, string, string, number, string],
    Vendor
  >,
  'createWeeklyProgress' : ActorMethod<
    [string, string, string, string, Array<string>],
    WeeklyProgress
  >,
  'escalateIssue' : ActorMethod<[string], [] | [Issue]>,
  'fulfillRequirement' : ActorMethod<[string, string], boolean>,
  'getAllIssues' : ActorMethod<[], Array<Issue>>,
  'getAllMaterials' : ActorMethod<[], Array<Material>>,
  'getAllPublicComplaints' : ActorMethod<[], Array<PublicComplaint>>,
  'getApprovals' : ActorMethod<[], Array<Approval>>,
  'getAttendanceByDate' : ActorMethod<[string], Array<AttendanceRecord>>,
  'getAttendanceByProject' : ActorMethod<[string], Array<Attendance>>,
  'getAttendanceBySite' : ActorMethod<[string], Array<AttendanceRecord>>,
  'getAttendanceByUser' : ActorMethod<[string], Array<AttendanceRecord>>,
  'getAttendanceStats' : ActorMethod<[string], AttendanceStats>,
  'getAuditLogs' : ActorMethod<[], Array<AuditLog>>,
  'getBillingStats' : ActorMethod<[string], BillingStats>,
  'getCallerUserRole' : ActorMethod<[], UserRole__1>,
  'getComplianceStats' : ActorMethod<[string], ComplianceStats>,
  'getConsumptionByMaterial' : ActorMethod<[string], Array<ConsumptionLog>>,
  'getConsumptionBySite' : ActorMethod<[string], Array<ConsumptionLog>>,
  'getConsumptionByTask' : ActorMethod<[string], Array<ConsumptionLog>>,
  'getConsumptionSummary' : ActorMethod<[string], Array<ConsumptionSummary>>,
  'getDashboardStats' : ActorMethod<[], DashboardStats>,
  'getDocumentsByProject' : ActorMethod<[string], Array<Document>>,
  'getExpensesByProject' : ActorMethod<[string], Array<Expense>>,
  'getExpensesBySite' : ActorMethod<[string], Array<BillingExpense>>,
  'getIssuesByProject' : ActorMethod<[string], Array<Issue>>,
  'getMaterialRequests' : ActorMethod<[], Array<MaterialRequest>>,
  'getMaterialsBySite' : ActorMethod<[string], Array<Material>>,
  'getProject' : ActorMethod<[string], [] | [Project]>,
  'getProjects' : ActorMethod<[], Array<Project>>,
  'getPublicComplaintsByProject' : ActorMethod<
    [string],
    Array<PublicComplaint>
  >,
  'getPurchaseOrder' : ActorMethod<[string], [] | [PurchaseOrder]>,
  'getRequirement' : ActorMethod<[string], [] | [Requirement]>,
  'getSite' : ActorMethod<[string], [] | [Site]>,
  'getSitePicturesByProject' : ActorMethod<[string], Array<SitePicture>>,
  'getSitePicturesByWeek' : ActorMethod<[string, string], Array<SitePicture>>,
  'getSiteStats' : ActorMethod<[], SiteStats>,
  'getSitesByUser' : ActorMethod<[string], Array<Site>>,
  'getTask' : ActorMethod<[string], [] | [Task]>,
  'getTasksByProject' : ActorMethod<[string], Array<Task>>,
  'getTestReport' : ActorMethod<[string], [] | [TestReport]>,
  'getTransfer' : ActorMethod<[string], [] | [Transfer]>,
  'getTripStats' : ActorMethod<[string], TripStats>,
  'getTripsByVehicle' : ActorMethod<[string], Array<TripLog>>,
  'getUsers' : ActorMethod<[], Array<User>>,
  'getWeeklyProgressByProject' : ActorMethod<[string], Array<WeeklyProgress>>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'listInvoicesBySite' : ActorMethod<[string], Array<Invoice>>,
  'listPurchaseOrders' : ActorMethod<[string], Array<PurchaseOrder>>,
  'listRequirements' : ActorMethod<[string], Array<Requirement>>,
  'listSites' : ActorMethod<[], Array<Site>>,
  'listTestReportsBySite' : ActorMethod<[string], Array<TestReport>>,
  'listTransfersBySite' : ActorMethod<[string], Array<Transfer>>,
  'listTripsBySite' : ActorMethod<[string], Array<TripLog>>,
  'listVendors' : ActorMethod<[], Array<Vendor>>,
  'logConsumption' : ActorMethod<
    [
      string,
      [] | [string],
      string,
      string,
      number,
      string,
      string,
      [] | [string],
    ],
    ConsumptionLog
  >,
  'markAttendance' : ActorMethod<
    [string, string, string, AttendanceMethod],
    Attendance
  >,
  'markDelivered' : ActorMethod<[string], boolean>,
  'markInvoicePaid' : ActorMethod<[string, string], boolean>,
  'processApproval' : ActorMethod<[string, boolean, string], [] | [Approval]>,
  'recordCheckIn' : ActorMethod<
    [
      string,
      [] | [string],
      [] | [number],
      [] | [number],
      boolean,
      [] | [string],
      string,
    ],
    AttendanceRecord
  >,
  'recordCheckOut' : ActorMethod<[string], boolean>,
  'rejectAttendance' : ActorMethod<[string], boolean>,
  'rejectInvoice' : ActorMethod<[string], boolean>,
  'rejectPurchaseOrder' : ActorMethod<[string], boolean>,
  'rejectRequirement' : ActorMethod<[string], boolean>,
  'rejectTestReport' : ActorMethod<[string], boolean>,
  'rejectTransfer' : ActorMethod<[string], boolean>,
  'rejectTrip' : ActorMethod<[string], boolean>,
  'reopenPublicComplaint' : ActorMethod<[bigint], boolean>,
  'resolvePublicComplaint' : ActorMethod<[bigint], boolean>,
  'seedSampleData' : ActorMethod<[], string>,
  'seedTasksAndMaterials' : ActorMethod<[], string>,
  'submitPurchaseOrder' : ActorMethod<[string], boolean>,
  'updateIssueStatus' : ActorMethod<[string, IssueStatus], [] | [Issue]>,
  'updateMaterial' : ActorMethod<[string, number], [] | [Material]>,
  'updateProjectProgress' : ActorMethod<[string, number], [] | [Project]>,
  'updateProjectStatus' : ActorMethod<[string, ProjectStatus], [] | [Project]>,
  'updatePurchaseOrder' : ActorMethod<
    [string, Array<PurchaseItem>, number, string, [] | [string]],
    boolean
  >,
  'updateRequirement' : ActorMethod<
    [
      string,
      string,
      number,
      string,
      Urgency,
      string,
      string,
      string,
      [] | [string],
    ],
    boolean
  >,
  'updateSiteStatus' : ActorMethod<[string, SiteStatus], boolean>,
  'updateTaskStatus' : ActorMethod<[string, TaskStatus], [] | [Task]>,
  'uploadDocument' : ActorMethod<[string, string, string, string], Document>,
  'uploadSitePicture' : ActorMethod<
    [string, string, string, string, boolean],
    SitePicture
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];